///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TrendyolTest
{
    public partial class AddToWishlistProduct
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Invoke_action_ProductNameSpan2(RepoItemInfo spantagInfo)
        {
            // TODO: Replace the following line with your code implementation.
            throw new NotImplementedException();
        }

        public void Get_value_ProductNameSpan(RepoItemInfo spantagInfo)
        {
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'spantagInfo' and assigning its value to variable 'ProductName_ToBeAddedWishlist'.", spantagInfo);
            ProductName_ToBeAddedWishlist = spantagInfo.FindAdapter<SpanTag>().Element.GetAttributeValueText("InnerText").Trim(); // trimmed to pretend errors
        }
    }

    public partial class AddToWishlist
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

    }

}
