///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddToCart recording.
    /// </summary>
    [TestModule("b26515fe-4cd1-4099-b3c7-e6127a6c7083", ModuleType.Recording, 1)]
    public partial class AddToCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static AddToCart instance = new AddToCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddToCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddToCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.trendyol.com/irmak/kup-seker-sargili-750-gr-p-43497508' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.trendyol.com/irmak/kup-seker-sargili-750-gr-p-43497508", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>' Küp Şeker Sargılı 750 gr 8690380009636 ') on item 'trendyol.SpanTagKuepŞekerSargılı750Gr869038'.", repo.trendyol.SpanTagKuepŞekerSargılı750Gr869038Info, new RecordItemIndex(1));
            Validate.AttributeContains(repo.trendyol.SpanTagKuepŞekerSargılı750Gr869038Info, "InnerText", " Küp Şeker Sargılı 750 gr 8690380009636 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.SepeteEkle' at Center.", repo.trendyol.SepeteEkleInfo, new RecordItemIndex(2));
            repo.trendyol.SepeteEkle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.Sepetim' at Center.", repo.trendyol.SepetimInfo, new RecordItemIndex(4));
            repo.trendyol.Sepetim.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Küp Şeker Sargılı 750 gr') on item 'trendyol.IrmakKuepŞekerSargılı750Gr'.", repo.trendyol.IrmakKuepŞekerSargılı750GrInfo, new RecordItemIndex(5));
            Validate.AttributeContains(repo.trendyol.IrmakKuepŞekerSargılı750GrInfo, "InnerText", "Küp Şeker Sargılı 750 gr");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
