///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddToWishlistProduct recording.
    /// </summary>
    [TestModule("4d691ce2-d48c-4c18-9e93-d38d0a4917f0", ModuleType.Recording, 1)]
    public partial class AddToWishlistProduct : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static AddToWishlistProduct instance = new AddToWishlistProduct();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddToWishlistProduct()
        {
            ProductName_ToBeAddedWishlist = "";
            ProductUrl_AddedToWishList = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddToWishlistProduct Instance
        {
            get { return instance; }
        }

#region Variables

        string _ProductName_ToBeAddedWishlist;

        /// <summary>
        /// Gets or sets the value of variable ProductName_ToBeAddedWishlist.
        /// </summary>
        [TestVariable("8025a691-2bb5-4e7c-b440-98c092d4107f")]
        public string ProductName_ToBeAddedWishlist
        {
            get { return _ProductName_ToBeAddedWishlist; }
            set { _ProductName_ToBeAddedWishlist = value; }
        }

        string _ProductUrl_AddedToWishList;

        /// <summary>
        /// Gets or sets the value of variable ProductUrl_AddedToWishList.
        /// </summary>
        [TestVariable("e4927ba3-b568-4361-8ece-4c118ba37c2a")]
        public string ProductUrl_AddedToWishList
        {
            get { return _ProductUrl_AddedToWishList; }
            set { _ProductUrl_AddedToWishList = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.ProductDetails.AddToFavoritesBtn'.", repo.trendyol.ProductDetails.AddToFavoritesBtnInfo, new RecordItemIndex(0));
            Validate.Exists(repo.trendyol.ProductDetails.AddToFavoritesBtnInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'trendyol.ProductDetails.AddToFavoritesBtn'.", repo.trendyol.ProductDetails.AddToFavoritesBtnInfo, new RecordItemIndex(1));
            repo.trendyol.ProductDetails.AddToFavoritesBtn.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'trendyol.ProductDetails.AddToFavoritesBtn'.", repo.trendyol.ProductDetails.AddToFavoritesBtnInfo, new RecordItemIndex(2));
            repo.trendyol.ProductDetails.AddToFavoritesBtn.As<WebElement>().PerformClick();
            Delay.Milliseconds(0);
            
            // Check if favorite button icon changed
            Report.Log(ReportLevel.Info, "Validation", "Check if favorite button icon changed\r\nValidating Exists on item 'trendyol.ProductDetails.AddedToFavoritesBtn'.", repo.trendyol.ProductDetails.AddedToFavoritesBtnInfo, new RecordItemIndex(3));
            Validate.Exists(repo.trendyol.ProductDetails.AddedToFavoritesBtnInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
