///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddToCartProduct recording.
    /// </summary>
    [TestModule("8e7f3ea2-bde1-48c0-9faa-75625e8a54c4", ModuleType.Recording, 1)]
    public partial class AddToCartProduct : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static AddToCartProduct instance = new AddToCartProduct();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddToCartProduct()
        {
            FirstProductLinkInCartPage = "";
            ProductUrl_AddedToCart = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddToCartProduct Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstProductLinkInCartPage;

        /// <summary>
        /// Gets or sets the value of variable FirstProductLinkInCartPage.
        /// </summary>
        [TestVariable("259c9e1e-fb8f-466a-a904-4270e3fa2490")]
        public string FirstProductLinkInCartPage
        {
            get { return _FirstProductLinkInCartPage; }
            set { _FirstProductLinkInCartPage = value; }
        }

        string _ProductUrl_AddedToCart;

        /// <summary>
        /// Gets or sets the value of variable ProductUrl_AddedToCart.
        /// </summary>
        [TestVariable("61be6eb4-ace3-4615-8a2d-0c8be74d66a1")]
        public string ProductUrl_AddedToCart
        {
            get { return _ProductUrl_AddedToCart; }
            set { _ProductUrl_AddedToCart = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Add to cart the product
            Report.Log(ReportLevel.Info, "Section", "Add to cart the product", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.AddToCartButton'.", repo.trendyol.AddToCartButtonInfo, new RecordItemIndex(1));
            Validate.Exists(repo.trendyol.AddToCartButtonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'trendyol.AddToCartButton'.", repo.trendyol.AddToCartButtonInfo, new RecordItemIndex(2));
            repo.trendyol.AddToCartButton.As<WebElement>().PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(3));
            Delay.Duration(3000, false);
            
            // Go To Cart Page
            Report.Log(ReportLevel.Info, "Section", "Go To Cart Page", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'trendyol.MyBasketButton'.", repo.trendyol.MyBasketButtonInfo, new RecordItemIndex(5));
            repo.trendyol.MyBasketButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(7));
            repo.trendyol.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Check product if exists in cart page
            Report.Log(ReportLevel.Info, "Section", "Check product if exists in cart page", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.SepetimTitle'.", repo.trendyol.SepetimTitleInfo, new RecordItemIndex(9));
            Validate.Exists(repo.trendyol.SepetimTitleInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.FirstProductLinkInCartPage'.", repo.trendyol.FirstProductLinkInCartPageInfo, new RecordItemIndex(10));
            Validate.Exists(repo.trendyol.FirstProductLinkInCartPageInfo);
            Delay.Milliseconds(0);
            
            Get_value_FirstProductLinkInCartPage(repo.trendyol.FirstProductLinkInCartPageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Href>$ProductUrl_AddedToCart) on item 'trendyol.FirstProductLinkInCartPage'.", repo.trendyol.FirstProductLinkInCartPageInfo, new RecordItemIndex(12));
            Validate.AttributeContains(repo.trendyol.FirstProductLinkInCartPageInfo, "Href", ProductUrl_AddedToCart);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
