///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddToWishlist recording.
    /// </summary>
    [TestModule("4d691ce2-d48c-4c18-9e93-d38d0a4917f0", ModuleType.Recording, 1)]
    public partial class AddToWishlist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static AddToWishlist instance = new AddToWishlist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddToWishlist()
        {
            ProductName = "iphone 11";
            WishlistItemToBeAdded = "iphone 11";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddToWishlist Instance
        {
            get { return instance; }
        }

#region Variables

        string _ProductName;

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("13f2fe6f-5eaf-4e3c-b188-dcf53d623ca1")]
        public string ProductName
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }

        string _WishlistItemToBeAdded;

        /// <summary>
        /// Gets or sets the value of variable WishlistItemToBeAdded.
        /// </summary>
        [TestVariable("29c84ac9-4c44-4e42-9634-8cab71679f83")]
        public string WishlistItemToBeAdded
        {
            get { return _WishlistItemToBeAdded; }
            set { _WishlistItemToBeAdded = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Get the name of product
            Report.Log(ReportLevel.Info, "Section", "Get the name of product", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking GetInnerHtml() on item 'trendyol.ProductNameSpan'.", repo.trendyol.ProductNameSpanInfo, new RecordItemIndex(1));
            WishlistItemToBeAdded = ValueConverter.ToString(repo.trendyol.ProductNameSpan.Element.InvokeActionWithText("GetInnerHtml"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", WishlistItemToBeAdded, new RecordItemIndex(2));
            
            // Add the product to wishlist
            Report.Log(ReportLevel.Info, "Section", "Add the product to wishlist", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.ProductDetails.AddToFavoritesBtn'.", repo.trendyol.ProductDetails.AddToFavoritesBtnInfo, new RecordItemIndex(4));
            Validate.Exists(repo.trendyol.ProductDetails.AddToFavoritesBtnInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'trendyol.ProductDetails.AddToFavoritesBtn' at Center.", repo.trendyol.ProductDetails.AddToFavoritesBtnInfo, new RecordItemIndex(5));
            repo.trendyol.ProductDetails.AddToFavoritesBtn.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.ProductDetails.AddToFavoritesBtn' at Center.", repo.trendyol.ProductDetails.AddToFavoritesBtnInfo, new RecordItemIndex(7));
            repo.trendyol.ProductDetails.AddToFavoritesBtn.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
