///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BlankFields recording.
    /// </summary>
    [TestModule("5a01f772-e1a0-498e-acc9-3dde4630dff9", ModuleType.Recording, 1)]
    public partial class BlankFields : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static BlankFields instance = new BlankFields();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BlankFields()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BlankFields Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.RegisterEmail' at Center.", repo.trendyol.RegisterEmailInfo, new RecordItemIndex(0));
            repo.trendyol.RegisterEmail.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '  ' with focus on 'trendyol.RegisterEmail'.", repo.trendyol.RegisterEmailInfo, new RecordItemIndex(1));
            repo.trendyol.RegisterEmail.PressKeys("  ");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeNotContains (TagValue!>' ') on item 'trendyol.RegisterEmail'.", repo.trendyol.RegisterEmailInfo, new RecordItemIndex(2));
                Validate.AttributeNotContains(repo.trendyol.RegisterEmailInfo, "TagValue", " ", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeNotContains (Value!>'') on item 'trendyol.RegisterEmail'.", repo.trendyol.RegisterEmailInfo, new RecordItemIndex(3));
                Validate.AttributeNotContains(repo.trendyol.RegisterEmailInfo, "Value", "", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.RegisterPasswordInput' at Center.", repo.trendyol.RegisterPasswordInputInfo, new RecordItemIndex(4));
            repo.trendyol.RegisterPasswordInput.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '  ' with focus on 'trendyol.RegisterEmail'.", repo.trendyol.RegisterEmailInfo, new RecordItemIndex(5));
            repo.trendyol.RegisterEmail.PressKeys("  ");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeNotContains (TagValue!>' ') on item 'trendyol.RegisterPasswordInput'.", repo.trendyol.RegisterPasswordInputInfo, new RecordItemIndex(6));
                Validate.AttributeNotContains(repo.trendyol.RegisterPasswordInputInfo, "TagValue", " ", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeNotContains (Value!>' ') on item 'trendyol.RegisterPasswordInput'.", repo.trendyol.RegisterPasswordInputInfo, new RecordItemIndex(7));
                Validate.AttributeNotContains(repo.trendyol.RegisterPasswordInputInfo, "Value", " ", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeNotEqual (TagValue!='True') on item 'trendyol.MarketingEmailCheckboxDiv'.", repo.trendyol.MarketingEmailCheckboxDivInfo, new RecordItemIndex(8));
                Validate.AttributeNotEqual(repo.trendyol.MarketingEmailCheckboxDivInfo, "TagValue", "True", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (TagValue='True') on item 'trendyol.PersonalDataCheckboxDiv'.", repo.trendyol.PersonalDataCheckboxDivInfo, new RecordItemIndex(9));
                Validate.AttributeEqual(repo.trendyol.PersonalDataCheckboxDivInfo, "TagValue", "True", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
