///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuyProducts recording.
    /// </summary>
    [TestModule("556cfc3c-9b34-4611-8949-9f94c8806a62", ModuleType.Recording, 1)]
    public partial class BuyProducts : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static BuyProducts instance = new BuyProducts();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuyProducts()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuyProducts Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.trendyol.com/irmak/kup-seker-sargili-750-gr-p-43497508?boutiqueId=613502&merchantId=457005' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.trendyol.com/irmak/kup-seker-sargili-750-gr-p-43497508?boutiqueId=613502&merchantId=457005", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.AddToCartButton' at Center.", repo.trendyol.AddToCartButtonInfo, new RecordItemIndex(1));
            repo.trendyol.AddToCartButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.trendyol.com/kahve-dunyasi/orta-kavrulmus-turk-kahvesi-100-gr-4-lu-paket-orta-kavrulmus-turk-kahvesi-100-gr-4-lu-paket-p-42720773' with browser 'Chrome' in maximized mode.", new RecordItemIndex(2));
            Host.Current.OpenBrowser("https://www.trendyol.com/kahve-dunyasi/orta-kavrulmus-turk-kahvesi-100-gr-4-lu-paket-orta-kavrulmus-turk-kahvesi-100-gr-4-lu-paket-p-42720773", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.AddToCartButton' at Center.", repo.trendyol.AddToCartButtonInfo, new RecordItemIndex(3));
            repo.trendyol.AddToCartButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.Sepetim' at Center.", repo.trendyol.SepetimInfo, new RecordItemIndex(4));
            repo.trendyol.Sepetim.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.ProceedToCheckoutButton' at Center.", repo.trendyol.ProceedToCheckoutButtonInfo, new RecordItemIndex(5));
            repo.trendyol.ProceedToCheckoutButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.CartPage.PCheckboxText' at Center.", repo.trendyol.CartPage.PCheckboxTextInfo, new RecordItemIndex(6));
            repo.trendyol.CartPage.PCheckboxText.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.CartPage.KaydetVeDevamEt' at Center.", repo.trendyol.CartPage.KaydetVeDevamEtInfo, new RecordItemIndex(7));
            repo.trendyol.CartPage.KaydetVeDevamEt.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.CartPage.OEdemeYap'.", repo.trendyol.CartPage.OEdemeYapInfo, new RecordItemIndex(8));
            Validate.Exists(repo.trendyol.CartPage.OEdemeYapInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
