///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckProductIfExistsInCartPage recording.
    /// </summary>
    [TestModule("1989ecd6-8298-42ae-b855-557a977949be", ModuleType.Recording, 1)]
    public partial class CheckProductIfExists : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static CheckProductIfExists instance = new CheckProductIfExists();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckProductIfExists()
        {
            ProductName_Cart = "";
            ProductName = "iphone 11";
            ProductNameWishlist = "";
            WishlistItemAdded = "";
            FirstProductLinkInCartPage = "";
            ProductUrl = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckProductIfExists Instance
        {
            get { return instance; }
        }

#region Variables

        string _ProductName_Cart;

        /// <summary>
        /// Gets or sets the value of variable ProductName_Cart.
        /// </summary>
        [TestVariable("2213b37e-3368-4cca-90e1-7000960dd46f")]
        public string ProductName_Cart
        {
            get { return _ProductName_Cart; }
            set { _ProductName_Cart = value; }
        }

        string _ProductName;

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("a78c973c-dd71-452b-8c03-980ea7eb8663")]
        public string ProductName
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }

        string _ProductNameWishlist;

        /// <summary>
        /// Gets or sets the value of variable ProductNameWishlist.
        /// </summary>
        [TestVariable("f9ed84dc-9ce3-4c35-8066-c6166c0e5170")]
        public string ProductNameWishlist
        {
            get { return _ProductNameWishlist; }
            set { _ProductNameWishlist = value; }
        }

        string _WishlistItemAdded;

        /// <summary>
        /// Gets or sets the value of variable WishlistItemAdded.
        /// </summary>
        [TestVariable("bbf24092-27a4-433d-b66d-e2736b237630")]
        public string WishlistItemAdded
        {
            get { return _WishlistItemAdded; }
            set { _WishlistItemAdded = value; }
        }

        string _FirstProductLinkInCartPage;

        /// <summary>
        /// Gets or sets the value of variable FirstProductLinkInCartPage.
        /// </summary>
        [TestVariable("941ed80d-0263-4baf-b722-c92fe88724c0")]
        public string FirstProductLinkInCartPage
        {
            get { return _FirstProductLinkInCartPage; }
            set { _FirstProductLinkInCartPage = value; }
        }

        string _ProductUrl;

        /// <summary>
        /// Gets or sets the value of variable ProductUrl.
        /// </summary>
        [TestVariable("f5424253-ce05-4ecb-aa81-3abf218e9122")]
        public string ProductUrl
        {
            get { return _ProductUrl; }
            set { _ProductUrl = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.FirstProductLinkInCartPage'.", repo.trendyol.FirstProductLinkInCartPageInfo, new RecordItemIndex(0));
            Validate.Exists(repo.trendyol.FirstProductLinkInCartPageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Href' from item 'trendyol.FirstProductLinkInCartPage' and assigning its value to variable 'FirstProductLinkInCartPage'.", repo.trendyol.FirstProductLinkInCartPageInfo, new RecordItemIndex(1));
            FirstProductLinkInCartPage = repo.trendyol.FirstProductLinkInCartPage.Element.GetAttributeValueText("Href");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual ($FirstProductLinkInCartPage=$ProductUrl) on item 'trendyol.FirstProductLinkInCartPage'.", repo.trendyol.FirstProductLinkInCartPageInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.trendyol.FirstProductLinkInCartPageInfo, FirstProductLinkInCartPage, ProductUrl);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
