///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckProductIfExistsInWishlistPage recording.
    /// </summary>
    [TestModule("e3ad91a5-9a88-458d-945d-89e577f77d50", ModuleType.Recording, 1)]
    public partial class CheckProductIfExistsInWishlistPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static CheckProductIfExistsInWishlistPage instance = new CheckProductIfExistsInWishlistPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckProductIfExistsInWishlistPage()
        {
            ProductName_Cart = "";
            ProductName = "iphone 11";
            ProductNameWishlistPage = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckProductIfExistsInWishlistPage Instance
        {
            get { return instance; }
        }

#region Variables

        string _ProductName_Cart;

        /// <summary>
        /// Gets or sets the value of variable ProductName_Cart.
        /// </summary>
        [TestVariable("e6b47195-0761-42bf-95f8-e91948cfcc89")]
        public string ProductName_Cart
        {
            get { return _ProductName_Cart; }
            set { _ProductName_Cart = value; }
        }

        string _ProductName;

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("ad3d84bc-f34d-4c2c-a43f-fb0448914614")]
        public string ProductName
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }

        string _ProductNameWishlistPage;

        /// <summary>
        /// Gets or sets the value of variable ProductNameWishlistPage.
        /// </summary>
        [TestVariable("e0bd456b-2525-4479-99fb-c410ebea2451")]
        public string ProductNameWishlistPage
        {
            get { return _ProductNameWishlistPage; }
            set { _ProductNameWishlistPage = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Title>$ProductNameWishlistPage) on item 'trendyol.ProductNameCartPage'.", repo.trendyol.ProductNameCartPageInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.trendyol.ProductNameCartPageInfo, "Title", ProductNameWishlistPage);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
