///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckIfNotLoggedIn recording.
    /// </summary>
    [TestModule("6492cabf-87ad-4dac-a3cf-62d0839f9783", ModuleType.Recording, 1)]
    public partial class CheckIfNotLoggedIn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static CheckIfNotLoggedIn instance = new CheckIfNotLoggedIn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckIfNotLoggedIn()
        {
            isLoggedIn = "false";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckIfNotLoggedIn Instance
        {
            get { return instance; }
        }

#region Variables

        string _isLoggedIn;

        /// <summary>
        /// Gets or sets the value of variable isLoggedIn.
        /// </summary>
        [TestVariable("9297a7b0-e0e8-4757-8246-fc402f81a769")]
        public string isLoggedIn
        {
            get { return _isLoggedIn; }
            set { _isLoggedIn = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.UserLoginContainer'.", repo.trendyol.UserLoginContainerInfo, new RecordItemIndex(0));
            Validate.Exists(repo.trendyol.UserLoginContainerInfo);
            Delay.Milliseconds(0);
            
            setLoggedInFalse(null);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
