///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToWishlistPageAndCheck recording.
    /// </summary>
    [TestModule("f0eeb7d1-01c5-4750-bda5-6431d616a4e8", ModuleType.Recording, 1)]
    public partial class GoToWishlistPageAndCheck : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static GoToWishlistPageAndCheck instance = new GoToWishlistPageAndCheck();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToWishlistPageAndCheck()
        {
            ProductName_ToBeAddedWishlist = "";
            ProductUrl_ToBeAddedWishlist = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToWishlistPageAndCheck Instance
        {
            get { return instance; }
        }

#region Variables

        string _ProductName_ToBeAddedWishlist;

        /// <summary>
        /// Gets or sets the value of variable ProductName_ToBeAddedWishlist.
        /// </summary>
        [TestVariable("b75f1bb6-f41a-45c8-aefd-1f4e1823f8d0")]
        public string ProductName_ToBeAddedWishlist
        {
            get { return _ProductName_ToBeAddedWishlist; }
            set { _ProductName_ToBeAddedWishlist = value; }
        }

        string _ProductUrl_ToBeAddedWishlist;

        /// <summary>
        /// Gets or sets the value of variable ProductUrl_ToBeAddedWishlist.
        /// </summary>
        [TestVariable("10d913cf-c7ef-4f23-a60b-087806bac558")]
        public string ProductUrl_ToBeAddedWishlist
        {
            get { return _ProductUrl_ToBeAddedWishlist; }
            set { _ProductUrl_ToBeAddedWishlist = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Go to wishlist page
            Report.Log(ReportLevel.Info, "Section", "Go to wishlist page", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'trendyol.MyFavoritesButton'.", repo.trendyol.MyFavoritesButtonInfo, new RecordItemIndex(1));
            repo.trendyol.MyFavoritesButton.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(3));
            repo.trendyol.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Check product if exists in wishlist page
            Report.Log(ReportLevel.Info, "Section", "Check product if exists in wishlist page", new RecordItemIndex(4));
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (PageUrl>'Favoriler') on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(5));
                Validate.AttributeContains(repo.trendyol.SelfInfo, "PageUrl", "Favoriler", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Href>$ProductUrl_ToBeAddedWishlist) on item 'trendyol.FirstProductLinkInWishlistPage'.", repo.trendyol.FirstProductLinkInWishlistPageInfo, new RecordItemIndex(6));
            Validate.AttributeContains(repo.trendyol.FirstProductLinkInWishlistPageInfo, "Href", ProductUrl_ToBeAddedWishlist);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
