///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToRegisterPage recording.
    /// </summary>
    [TestModule("b23aa907-f7be-4af2-96d6-901520759c17", ModuleType.Recording, 1)]
    public partial class GoToRegisterPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static GoToRegisterPage instance = new GoToRegisterPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToRegisterPage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToRegisterPage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Go to register page
            Report.Log(ReportLevel.Info, "Section", "Go to register page", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.LoginButton'.", repo.trendyol.LoginButtonInfo, new RecordItemIndex(1));
            Validate.Exists(repo.trendyol.LoginButtonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'trendyol.LoginButton'.", repo.trendyol.LoginButtonInfo, new RecordItemIndex(2));
            repo.trendyol.LoginButton.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'trendyol.LoginButton'.", repo.trendyol.LoginButtonInfo, new RecordItemIndex(3));
            repo.trendyol.LoginButton.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(4));
            repo.trendyol.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            // Switch to register tab
            Report.Log(ReportLevel.Info, "Section", "Switch to register tab", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.RegisterPage.RegisterTabButton'.", repo.trendyol.RegisterPage.RegisterTabButtonInfo, new RecordItemIndex(7));
            Validate.Exists(repo.trendyol.RegisterPage.RegisterTabButtonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'trendyol.RegisterPage.RegisterTabButton'.", repo.trendyol.RegisterPage.RegisterTabButtonInfo, new RecordItemIndex(8));
            repo.trendyol.RegisterPage.RegisterTabButton.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'trendyol.RegisterPage.RegisterTabButton'.", repo.trendyol.RegisterPage.RegisterTabButtonInfo, new RecordItemIndex(9));
            repo.trendyol.RegisterPage.RegisterTabButton.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            // Validate is switched to register tab
            Report.Log(ReportLevel.Info, "Section", "Validate is switched to register tab", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.RegisterPage.RegisterTabContainer'.", repo.trendyol.RegisterPage.RegisterTabContainerInfo, new RecordItemIndex(12));
            Validate.Exists(repo.trendyol.RegisterPage.RegisterTabContainerInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
