///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToCartPage recording.
    /// </summary>
    [TestModule("1c82fb79-0c39-4d27-8f1b-5bc8e0558003", ModuleType.Recording, 1)]
    public partial class GoToCartPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static GoToCartPage instance = new GoToCartPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToCartPage()
        {
            CartUrl = "https://www.trendyol.com/sepet";
            ProductName_Cart = "";
            ProductName = "iphone 11";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToCartPage Instance
        {
            get { return instance; }
        }

#region Variables

        string _CartUrl;

        /// <summary>
        /// Gets or sets the value of variable CartUrl.
        /// </summary>
        [TestVariable("6b022691-510c-4429-90d1-e2adb64fa641")]
        public string CartUrl
        {
            get { return _CartUrl; }
            set { _CartUrl = value; }
        }

        string _ProductName_Cart;

        /// <summary>
        /// Gets or sets the value of variable ProductName_Cart.
        /// </summary>
        [TestVariable("93e6ee0f-78d0-4a01-b1de-277280783197")]
        public string ProductName_Cart
        {
            get { return _ProductName_Cart; }
            set { _ProductName_Cart = value; }
        }

        string _ProductName;

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("8e6eb13d-1b5e-4f51-bf94-22b27ea4c1ad")]
        public string ProductName
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Navigate(variable $CartUrl) on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(0));
            repo.trendyol.Self.Navigate(CartUrl);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(1));
            repo.trendyol.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
