///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoToWishlistPage recording.
    /// </summary>
    [TestModule("7edaa8a0-43e4-4fd5-a1b2-0d9e866625c1", ModuleType.Recording, 1)]
    public partial class GoToWishlistPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static GoToWishlistPage instance = new GoToWishlistPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoToWishlistPage()
        {
            WishlistPageUrl = "https://www.trendyol.com/Hesabim/Favoriler";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoToWishlistPage Instance
        {
            get { return instance; }
        }

#region Variables

        string _WishlistPageUrl;

        /// <summary>
        /// Gets or sets the value of variable WishlistPageUrl.
        /// </summary>
        [TestVariable("06562ce9-d07a-4501-8658-d9e90bd27a05")]
        public string WishlistPageUrl
        {
            get { return _WishlistPageUrl; }
            set { _WishlistPageUrl = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Navigate(variable $WishlistPageUrl) on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(0));
            repo.trendyol.Self.Navigate(WishlistPageUrl);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
