///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("da7341ca-6f1c-4ead-88ac-c34a680560cd", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.trendyol.com/giris' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.trendyol.com/giris", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.LoginPage.LoginEmail' at Center.", repo.trendyol.LoginPage.LoginEmailInfo, new RecordItemIndex(1));
            repo.trendyol.LoginPage.LoginEmail.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'alperenkumcu@gmail.com' on item 'trendyol.LoginPage.LoginEmail'.", repo.trendyol.LoginPage.LoginEmailInfo, new RecordItemIndex(2));
            repo.trendyol.LoginPage.LoginEmail.Element.SetAttributeValue("Value", "alperenkumcu@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.LoginPage.LoginPasswordInput' at Center.", repo.trendyol.LoginPage.LoginPasswordInputInfo, new RecordItemIndex(3));
            repo.trendyol.LoginPage.LoginPasswordInput.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '23mSBg9nC&v9nnR' on item 'trendyol.LoginPage.LoginPasswordInput'.", repo.trendyol.LoginPage.LoginPasswordInputInfo, new RecordItemIndex(4));
            repo.trendyol.LoginPage.LoginPasswordInput.Element.SetAttributeValue("Value", "23mSBg9nC&v9nnR");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'trendyol.LoginPage.LoginButton' at Center.", repo.trendyol.LoginPage.LoginButtonInfo, new RecordItemIndex(5));
            repo.trendyol.LoginPage.LoginButton.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'trendyol.LoginPage.LoginButton' at Center.", repo.trendyol.LoginPage.LoginButtonInfo, new RecordItemIndex(6));
            repo.trendyol.LoginPage.LoginButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Hesabım') on item 'trendyol.MyAccount'.", repo.trendyol.MyAccountInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.trendyol.MyAccountInfo, "InnerText", "Hesabım");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
