///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchProduct recording.
    /// </summary>
    [TestModule("ca6ae3b1-a41f-44f9-b54f-802c7f41ad4c", ModuleType.Recording, 1)]
    public partial class SearchProduct : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolTestRepository repository.
        /// </summary>
        public static TrendyolTestRepository repo = TrendyolTestRepository.Instance;

        static SearchProduct instance = new SearchProduct();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchProduct()
        {
            SearchKeyword = "iphone 11";
            ProductUrl = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchProduct Instance
        {
            get { return instance; }
        }

#region Variables

        string _SearchKeyword;

        /// <summary>
        /// Gets or sets the value of variable SearchKeyword.
        /// </summary>
        [TestVariable("4fddce82-48ba-4132-9cdc-bc9936dbb388")]
        public string SearchKeyword
        {
            get { return _SearchKeyword; }
            set { _SearchKeyword = value; }
        }

        string _ProductUrl;

        /// <summary>
        /// Gets or sets the value of variable ProductUrl.
        /// </summary>
        [TestVariable("fc841108-028a-4233-baab-3f61f1810d8e")]
        public string ProductUrl
        {
            get { return _ProductUrl; }
            set { _ProductUrl = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(0));
            repo.trendyol.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(1));
            Delay.Duration(3000, false);
            
            // Search Product
            Report.Log(ReportLevel.Info, "Section", "Search Product", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'trendyol.SearchInput'.", repo.trendyol.SearchInputInfo, new RecordItemIndex(3));
            repo.trendyol.SearchInput.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'trendyol.SearchInput'.", repo.trendyol.SearchInputInfo, new RecordItemIndex(4));
            repo.trendyol.SearchInput.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$SearchKeyword' on item 'trendyol.SearchInput'.", repo.trendyol.SearchInputInfo, new RecordItemIndex(6));
            repo.trendyol.SearchInput.Element.SetAttributeValue("Value", SearchKeyword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(8));
            repo.trendyol.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'trendyol.SearchInput'.", repo.trendyol.SearchInputInfo, new RecordItemIndex(9));
            Keyboard.PrepareFocus(repo.trendyol.SearchInput);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            // Go to Details Page of First Product in search results
            Report.Log(ReportLevel.Info, "Section", "Go to Details Page of First Product in search results", new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'trendyol.FirstProductLinkInSearchPage'.", repo.trendyol.FirstProductLinkInSearchPageInfo, new RecordItemIndex(11));
            Validate.Exists(repo.trendyol.FirstProductLinkInSearchPageInfo);
            Delay.Milliseconds(0);
            
            Get_value_FirstProductLinkInSearchPage1(repo.trendyol.FirstProductLinkInSearchPageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Navigate(variable $ProductUrl) on item 'trendyol'.", repo.trendyol.SelfInfo, new RecordItemIndex(13));
            repo.trendyol.Self.Navigate(ProductUrl);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
