///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TrendyolTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("62222601-220c-44bf-a55a-74347c474ca6")]
    public partial class TrendyolTestRepository : RepoGenBaseFolder
    {
        static TrendyolTestRepository instance = new TrendyolTestRepository();
        TrendyolTestRepositoryFolders.TrendyolAppFolder _trendyol;

        /// <summary>
        /// Gets the singleton class instance representing the TrendyolTestRepository element repository.
        /// </summary>
        [RepositoryFolder("62222601-220c-44bf-a55a-74347c474ca6")]
        public static TrendyolTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TrendyolTestRepository() 
            : base("TrendyolTestRepository", "/", null, 0, false, "62222601-220c-44bf-a55a-74347c474ca6", ".\\RepositoryImages\\TrendyolTestRepository62222601.rximgres")
        {
            _trendyol = new TrendyolTestRepositoryFolders.TrendyolAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("62222601-220c-44bf-a55a-74347c474ca6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The trendyol folder.
        /// </summary>
        [RepositoryFolder("20f41ba7-5a28-40ae-a06a-52591aa57649")]
        public virtual TrendyolTestRepositoryFolders.TrendyolAppFolder trendyol
        {
            get { return _trendyol; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TrendyolTestRepositoryFolders
    {
        /// <summary>
        /// The TrendyolAppFolder folder.
        /// </summary>
        [RepositoryFolder("20f41ba7-5a28-40ae-a06a-52591aa57649")]
        public partial class TrendyolAppFolder : RepoGenBaseFolder
        {
            TrendyolTestRepositoryFolders.RegisterPageFolder _registerpage;
            TrendyolTestRepositoryFolders.ProductDetailsFolder _productdetails;
            TrendyolTestRepositoryFolders.CartPageFolder _cartpage;
            TrendyolTestRepositoryFolders.LoginPageFolder _loginpage;
            RepoItemInfo _personaldatacheckboxdivInfo;
            RepoItemInfo _mybasketbuttonInfo;
            RepoItemInfo _myfavoritesbuttonInfo;
            RepoItemInfo _addtocartbuttonInfo;
            RepoItemInfo _proceedtocheckoutbuttonInfo;
            RepoItemInfo _searchinputInfo;
            RepoItemInfo _logoutbuttonInfo;
            RepoItemInfo _myaccountbuttonInfo;
            RepoItemInfo _firstproductnamewishlistInfo;
            RepoItemInfo _firstproductlinkinsearchpageInfo;
            RepoItemInfo _firstproductlinkinwishlistpageInfo;
            RepoItemInfo _firstproductlinkincartpageInfo;
            RepoItemInfo _errorboxwrapperInfo;
            RepoItemInfo _userlogincontainerInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _sepetimtitleInfo;

            /// <summary>
            /// Creates a new trendyol  folder.
            /// </summary>
            public TrendyolAppFolder(RepoGenBaseFolder parentFolder) :
                    base("trendyol", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "20f41ba7-5a28-40ae-a06a-52591aa57649", "")
            {
                _registerpage = new TrendyolTestRepositoryFolders.RegisterPageFolder(this);
                _productdetails = new TrendyolTestRepositoryFolders.ProductDetailsFolder(this);
                _cartpage = new TrendyolTestRepositoryFolders.CartPageFolder(this);
                _loginpage = new TrendyolTestRepositoryFolders.LoginPageFolder(this);
                _personaldatacheckboxdivInfo = new RepoItemInfo(this, "PersonalDataCheckboxDiv", ".//div[@name='personal-data-error']", 30000, null, "3f4881b2-5705-49f0-bf25-38d7b2d1244a");
                _mybasketbuttonInfo = new RepoItemInfo(this, "MyBasketButton", ".//p[@innertext='Sepetim']", 30000, null, "30140022-9b65-4374-84e9-c4f939a146bc");
                _myfavoritesbuttonInfo = new RepoItemInfo(this, "MyFavoritesButton", ".//a[@class~'account-favorites']", 30000, null, "c72bcbf4-c7fb-48a5-98bc-c7a296d64a5a");
                _addtocartbuttonInfo = new RepoItemInfo(this, "AddToCartButton", ".//*[@class='add-to-basket']", 30000, null, "145f3143-f3e4-4cf9-9a65-31ce6beb267b");
                _proceedtocheckoutbuttonInfo = new RepoItemInfo(this, "ProceedToCheckoutButton", ".//span[@innertext='Sepeti Onayla']", 30000, null, "87145e4a-8258-4631-8aa9-bd75ad265f70");
                _searchinputInfo = new RepoItemInfo(this, "SearchInput", ".//div[@id='sfx-discovery-search-suggestions']//input", 30000, null, "9802ff52-3124-481d-8de5-384343e9aa44");
                _logoutbuttonInfo = new RepoItemInfo(this, "LogoutButton", ".//*[@class='loggedin-account-item']/p[text()~'Çıkış']", 30000, null, "ec3932f7-c41f-4335-b62f-4cbf1a883e25");
                _myaccountbuttonInfo = new RepoItemInfo(this, "MyAccountButton", ".//p[text()~'Hesabım']", 30000, null, "7c14b9ca-221d-4a87-8076-2e1f24a83769");
                _firstproductnamewishlistInfo = new RepoItemInfo(this, "FirstProductNameWishlist", ".//span[@class~'prdct-desc-cntnr-name'][1]", 30000, null, "156233b6-dd73-4971-b504-f2446de3774e");
                _firstproductlinkinsearchpageInfo = new RepoItemInfo(this, "FirstProductLinkInSearchPage", ".//div[@class~'p-card-chldrn-cntnr']/a", 30000, null, "d643e97f-8fa0-444e-bd58-81129fbd9738");
                _firstproductlinkinwishlistpageInfo = new RepoItemInfo(this, "FirstProductLinkInWishlistPage", ".//a[@class~'p-card-chldrn-cntnr']", 30000, null, "cc9739c1-2ad2-49e2-8513-9477a7a6bbdb");
                _firstproductlinkincartpageInfo = new RepoItemInfo(this, "FirstProductLinkInCartPage", ".//div[@class='pb-basket-item']/a", 30000, null, "562e393f-d3ee-4c03-8464-d3d86e336eaf");
                _errorboxwrapperInfo = new RepoItemInfo(this, "ErrorBoxWrapper", ".//div[#'error-box-wrapper']", 30000, null, "2bbe84ec-347e-4ad4-9eca-b0126a57744f");
                _userlogincontainerInfo = new RepoItemInfo(this, "UserLoginContainer", ".//div[@class~'user-login-container']", 30000, null, "ebc77187-2468-4237-b8fb-f91a0077d815");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//div[@class~'user-notloggedin-container']/div[@class~'login-button']", 30000, null, "e4781eb1-e4f6-4a35-8183-9f3abf8e8d92");
                _sepetimtitleInfo = new RepoItemInfo(this, "SepetimTitle", ".//div[@class~'pb-header' and text()~'Sepetim']", 30000, null, "036f9130-7ed6-416e-b979-8e36348bde90");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("20f41ba7-5a28-40ae-a06a-52591aa57649")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("20f41ba7-5a28-40ae-a06a-52591aa57649")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PersonalDataCheckboxDiv item.
            /// </summary>
            [RepositoryItem("3f4881b2-5705-49f0-bf25-38d7b2d1244a")]
            public virtual Ranorex.DivTag PersonalDataCheckboxDiv
            {
                get
                {
                    return _personaldatacheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalDataCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("3f4881b2-5705-49f0-bf25-38d7b2d1244a")]
            public virtual RepoItemInfo PersonalDataCheckboxDivInfo
            {
                get
                {
                    return _personaldatacheckboxdivInfo;
                }
            }

            /// <summary>
            /// The MyBasketButton item.
            /// </summary>
            [RepositoryItem("30140022-9b65-4374-84e9-c4f939a146bc")]
            public virtual Ranorex.PTag MyBasketButton
            {
                get
                {
                    return _mybasketbuttonInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MyBasketButton item info.
            /// </summary>
            [RepositoryItemInfo("30140022-9b65-4374-84e9-c4f939a146bc")]
            public virtual RepoItemInfo MyBasketButtonInfo
            {
                get
                {
                    return _mybasketbuttonInfo;
                }
            }

            /// <summary>
            /// The MyFavoritesButton item.
            /// </summary>
            [RepositoryItem("c72bcbf4-c7fb-48a5-98bc-c7a296d64a5a")]
            public virtual Ranorex.ATag MyFavoritesButton
            {
                get
                {
                    return _myfavoritesbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MyFavoritesButton item info.
            /// </summary>
            [RepositoryItemInfo("c72bcbf4-c7fb-48a5-98bc-c7a296d64a5a")]
            public virtual RepoItemInfo MyFavoritesButtonInfo
            {
                get
                {
                    return _myfavoritesbuttonInfo;
                }
            }

            /// <summary>
            /// The AddToCartButton item.
            /// </summary>
            [RepositoryItem("145f3143-f3e4-4cf9-9a65-31ce6beb267b")]
            public virtual Ranorex.Unknown AddToCartButton
            {
                get
                {
                    return _addtocartbuttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AddToCartButton item info.
            /// </summary>
            [RepositoryItemInfo("145f3143-f3e4-4cf9-9a65-31ce6beb267b")]
            public virtual RepoItemInfo AddToCartButtonInfo
            {
                get
                {
                    return _addtocartbuttonInfo;
                }
            }

            /// <summary>
            /// The ProceedToCheckoutButton item.
            /// </summary>
            [RepositoryItem("87145e4a-8258-4631-8aa9-bd75ad265f70")]
            public virtual Ranorex.SpanTag ProceedToCheckoutButton
            {
                get
                {
                    return _proceedtocheckoutbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProceedToCheckoutButton item info.
            /// </summary>
            [RepositoryItemInfo("87145e4a-8258-4631-8aa9-bd75ad265f70")]
            public virtual RepoItemInfo ProceedToCheckoutButtonInfo
            {
                get
                {
                    return _proceedtocheckoutbuttonInfo;
                }
            }

            /// <summary>
            /// The SearchInput item.
            /// </summary>
            [RepositoryItem("9802ff52-3124-481d-8de5-384343e9aa44")]
            public virtual Ranorex.InputTag SearchInput
            {
                get
                {
                    return _searchinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchInput item info.
            /// </summary>
            [RepositoryItemInfo("9802ff52-3124-481d-8de5-384343e9aa44")]
            public virtual RepoItemInfo SearchInputInfo
            {
                get
                {
                    return _searchinputInfo;
                }
            }

            /// <summary>
            /// The LogoutButton item.
            /// </summary>
            [RepositoryItem("ec3932f7-c41f-4335-b62f-4cbf1a883e25")]
            public virtual Ranorex.PTag LogoutButton
            {
                get
                {
                    return _logoutbuttonInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The LogoutButton item info.
            /// </summary>
            [RepositoryItemInfo("ec3932f7-c41f-4335-b62f-4cbf1a883e25")]
            public virtual RepoItemInfo LogoutButtonInfo
            {
                get
                {
                    return _logoutbuttonInfo;
                }
            }

            /// <summary>
            /// The MyAccountButton item.
            /// </summary>
            [RepositoryItem("7c14b9ca-221d-4a87-8076-2e1f24a83769")]
            public virtual Ranorex.PTag MyAccountButton
            {
                get
                {
                    return _myaccountbuttonInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MyAccountButton item info.
            /// </summary>
            [RepositoryItemInfo("7c14b9ca-221d-4a87-8076-2e1f24a83769")]
            public virtual RepoItemInfo MyAccountButtonInfo
            {
                get
                {
                    return _myaccountbuttonInfo;
                }
            }

            /// <summary>
            /// The FirstProductNameWishlist item.
            /// </summary>
            [RepositoryItem("156233b6-dd73-4971-b504-f2446de3774e")]
            public virtual Ranorex.SpanTag FirstProductNameWishlist
            {
                get
                {
                    return _firstproductnamewishlistInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The FirstProductNameWishlist item info.
            /// </summary>
            [RepositoryItemInfo("156233b6-dd73-4971-b504-f2446de3774e")]
            public virtual RepoItemInfo FirstProductNameWishlistInfo
            {
                get
                {
                    return _firstproductnamewishlistInfo;
                }
            }

            /// <summary>
            /// The FirstProductLinkInSearchPage item.
            /// </summary>
            [RepositoryItem("d643e97f-8fa0-444e-bd58-81129fbd9738")]
            public virtual Ranorex.ATag FirstProductLinkInSearchPage
            {
                get
                {
                    return _firstproductlinkinsearchpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FirstProductLinkInSearchPage item info.
            /// </summary>
            [RepositoryItemInfo("d643e97f-8fa0-444e-bd58-81129fbd9738")]
            public virtual RepoItemInfo FirstProductLinkInSearchPageInfo
            {
                get
                {
                    return _firstproductlinkinsearchpageInfo;
                }
            }

            /// <summary>
            /// The FirstProductLinkInWishlistPage item.
            /// </summary>
            [RepositoryItem("cc9739c1-2ad2-49e2-8513-9477a7a6bbdb")]
            public virtual Ranorex.ATag FirstProductLinkInWishlistPage
            {
                get
                {
                    return _firstproductlinkinwishlistpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FirstProductLinkInWishlistPage item info.
            /// </summary>
            [RepositoryItemInfo("cc9739c1-2ad2-49e2-8513-9477a7a6bbdb")]
            public virtual RepoItemInfo FirstProductLinkInWishlistPageInfo
            {
                get
                {
                    return _firstproductlinkinwishlistpageInfo;
                }
            }

            /// <summary>
            /// The FirstProductLinkInCartPage item.
            /// </summary>
            [RepositoryItem("562e393f-d3ee-4c03-8464-d3d86e336eaf")]
            public virtual Ranorex.ATag FirstProductLinkInCartPage
            {
                get
                {
                    return _firstproductlinkincartpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FirstProductLinkInCartPage item info.
            /// </summary>
            [RepositoryItemInfo("562e393f-d3ee-4c03-8464-d3d86e336eaf")]
            public virtual RepoItemInfo FirstProductLinkInCartPageInfo
            {
                get
                {
                    return _firstproductlinkincartpageInfo;
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item.
            /// </summary>
            [RepositoryItem("2bbe84ec-347e-4ad4-9eca-b0126a57744f")]
            public virtual Ranorex.DivTag ErrorBoxWrapper
            {
                get
                {
                    return _errorboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item info.
            /// </summary>
            [RepositoryItemInfo("2bbe84ec-347e-4ad4-9eca-b0126a57744f")]
            public virtual RepoItemInfo ErrorBoxWrapperInfo
            {
                get
                {
                    return _errorboxwrapperInfo;
                }
            }

            /// <summary>
            /// The UserLoginContainer item.
            /// </summary>
            [RepositoryItem("ebc77187-2468-4237-b8fb-f91a0077d815")]
            public virtual Ranorex.DivTag UserLoginContainer
            {
                get
                {
                    return _userlogincontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UserLoginContainer item info.
            /// </summary>
            [RepositoryItemInfo("ebc77187-2468-4237-b8fb-f91a0077d815")]
            public virtual RepoItemInfo UserLoginContainerInfo
            {
                get
                {
                    return _userlogincontainerInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("e4781eb1-e4f6-4a35-8183-9f3abf8e8d92")]
            public virtual Ranorex.DivTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("e4781eb1-e4f6-4a35-8183-9f3abf8e8d92")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The SepetimTitle item.
            /// </summary>
            [RepositoryItem("036f9130-7ed6-416e-b979-8e36348bde90")]
            public virtual Ranorex.DivTag SepetimTitle
            {
                get
                {
                    return _sepetimtitleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepetimTitle item info.
            /// </summary>
            [RepositoryItemInfo("036f9130-7ed6-416e-b979-8e36348bde90")]
            public virtual RepoItemInfo SepetimTitleInfo
            {
                get
                {
                    return _sepetimtitleInfo;
                }
            }

            /// <summary>
            /// The RegisterPage folder.
            /// </summary>
            [RepositoryFolder("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual TrendyolTestRepositoryFolders.RegisterPageFolder RegisterPage
            {
                get { return _registerpage; }
            }

            /// <summary>
            /// The ProductDetails folder.
            /// </summary>
            [RepositoryFolder("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual TrendyolTestRepositoryFolders.ProductDetailsFolder ProductDetails
            {
                get { return _productdetails; }
            }

            /// <summary>
            /// The CartPage folder.
            /// </summary>
            [RepositoryFolder("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual TrendyolTestRepositoryFolders.CartPageFolder CartPage
            {
                get { return _cartpage; }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual TrendyolTestRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }
        }

        /// <summary>
        /// The RegisterPageFolder folder.
        /// </summary>
        [RepositoryFolder("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
        public partial class RegisterPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _personalcheckboxdivInfo;
            RepoItemInfo _marketingemailcheckboxdivInfo;
            RepoItemInfo _marketingcheckboxdivInfo;
            RepoItemInfo _registerbuttonInfo;
            RepoItemInfo _registeremailinputInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _registertabbuttonInfo;
            RepoItemInfo _registertabcontainerInfo;

            /// <summary>
            /// Creates a new RegisterPage  folder.
            /// </summary>
            public RegisterPageFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterPage", "", parentFolder, 30000, null, false, "92ff70e5-3c16-4368-8ec6-a1252c5236f8", "")
            {
                _personalcheckboxdivInfo = new RepoItemInfo(this, "PersonalCheckboxDiv", ".//div[@class='personal-checkbox']", 30000, null, "49e66d49-8381-4708-a1a0-fe36dc994057");
                _marketingemailcheckboxdivInfo = new RepoItemInfo(this, "MarketingEmailCheckboxDiv", ".//div[@name='marketing-email']", 30000, null, "e3abd9cc-54b9-45a1-9bf9-141a9ab18028");
                _marketingcheckboxdivInfo = new RepoItemInfo(this, "MarketingCheckboxDiv", ".//div[@class='marketing-checkbox']", 30000, null, "cb1d2aaf-e139-4612-b6b1-c9311b50efc6");
                _registerbuttonInfo = new RepoItemInfo(this, "RegisterButton", ".//form/button", 30000, null, "ea0e4a66-6c0b-4f1a-b677-e867cd149887");
                _registeremailinputInfo = new RepoItemInfo(this, "RegisterEmailInput", ".//input[#'register-email']", 30000, null, "85df90b8-1a3b-4517-a07b-f17096ccda49");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", 30000, null, "7556e76c-f236-4a6a-bc49-bfbee4e070b1");
                _registertabbuttonInfo = new RepoItemInfo(this, "RegisterTabButton", ".//div[@class~'header-buttons']/*[text()~'Üye Ol']", 30000, null, "f4da5022-77f0-43cc-b8e3-7d639c9b1891");
                _registertabcontainerInfo = new RepoItemInfo(this, "RegisterTabContainer", ".//div[@class~'q-layout register']", 30000, null, "c9bff0e1-a362-48fc-b19c-6d09b44fe94e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PersonalCheckboxDiv item.
            /// </summary>
            [RepositoryItem("49e66d49-8381-4708-a1a0-fe36dc994057")]
            public virtual Ranorex.DivTag PersonalCheckboxDiv
            {
                get
                {
                    return _personalcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("49e66d49-8381-4708-a1a0-fe36dc994057")]
            public virtual RepoItemInfo PersonalCheckboxDivInfo
            {
                get
                {
                    return _personalcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The MarketingEmailCheckboxDiv item.
            /// </summary>
            [RepositoryItem("e3abd9cc-54b9-45a1-9bf9-141a9ab18028")]
            public virtual Ranorex.DivTag MarketingEmailCheckboxDiv
            {
                get
                {
                    return _marketingemailcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MarketingEmailCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("e3abd9cc-54b9-45a1-9bf9-141a9ab18028")]
            public virtual RepoItemInfo MarketingEmailCheckboxDivInfo
            {
                get
                {
                    return _marketingemailcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The MarketingCheckboxDiv item.
            /// </summary>
            [RepositoryItem("cb1d2aaf-e139-4612-b6b1-c9311b50efc6")]
            public virtual Ranorex.DivTag MarketingCheckboxDiv
            {
                get
                {
                    return _marketingcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MarketingCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("cb1d2aaf-e139-4612-b6b1-c9311b50efc6")]
            public virtual RepoItemInfo MarketingCheckboxDivInfo
            {
                get
                {
                    return _marketingcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The RegisterButton item.
            /// </summary>
            [RepositoryItem("ea0e4a66-6c0b-4f1a-b677-e867cd149887")]
            public virtual Ranorex.ButtonTag RegisterButton
            {
                get
                {
                    return _registerbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RegisterButton item info.
            /// </summary>
            [RepositoryItemInfo("ea0e4a66-6c0b-4f1a-b677-e867cd149887")]
            public virtual RepoItemInfo RegisterButtonInfo
            {
                get
                {
                    return _registerbuttonInfo;
                }
            }

            /// <summary>
            /// The RegisterEmailInput item.
            /// </summary>
            [RepositoryItem("85df90b8-1a3b-4517-a07b-f17096ccda49")]
            public virtual Ranorex.InputTag RegisterEmailInput
            {
                get
                {
                    return _registeremailinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmailInput item info.
            /// </summary>
            [RepositoryItemInfo("85df90b8-1a3b-4517-a07b-f17096ccda49")]
            public virtual RepoItemInfo RegisterEmailInputInfo
            {
                get
                {
                    return _registeremailinputInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("7556e76c-f236-4a6a-bc49-bfbee4e070b1")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("7556e76c-f236-4a6a-bc49-bfbee4e070b1")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The RegisterTabButton item.
            /// </summary>
            [RepositoryItem("f4da5022-77f0-43cc-b8e3-7d639c9b1891")]
            public virtual Ranorex.Unknown RegisterTabButton
            {
                get
                {
                    return _registertabbuttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The RegisterTabButton item info.
            /// </summary>
            [RepositoryItemInfo("f4da5022-77f0-43cc-b8e3-7d639c9b1891")]
            public virtual RepoItemInfo RegisterTabButtonInfo
            {
                get
                {
                    return _registertabbuttonInfo;
                }
            }

            /// <summary>
            /// The RegisterTabContainer item.
            /// </summary>
            [RepositoryItem("c9bff0e1-a362-48fc-b19c-6d09b44fe94e")]
            public virtual Ranorex.DivTag RegisterTabContainer
            {
                get
                {
                    return _registertabcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RegisterTabContainer item info.
            /// </summary>
            [RepositoryItemInfo("c9bff0e1-a362-48fc-b19c-6d09b44fe94e")]
            public virtual RepoItemInfo RegisterTabContainerInfo
            {
                get
                {
                    return _registertabcontainerInfo;
                }
            }
        }

        /// <summary>
        /// The ProductDetailsFolder folder.
        /// </summary>
        [RepositoryFolder("27698d01-8ea9-4b65-9edd-3224afe26aef")]
        public partial class ProductDetailsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addtofavoritesbtnInfo;
            RepoItemInfo _addedtofavoritesbtnInfo;

            /// <summary>
            /// Creates a new ProductDetails  folder.
            /// </summary>
            public ProductDetailsFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductDetails", "", parentFolder, 30000, null, false, "27698d01-8ea9-4b65-9edd-3224afe26aef", "")
            {
                _addtofavoritesbtnInfo = new RepoItemInfo(this, "AddToFavoritesBtn", ".//div[@class='container-right-content']//*[@class='fv']", 30000, null, "8171e99b-7f37-4cb1-af52-086de2980edf");
                _addedtofavoritesbtnInfo = new RepoItemInfo(this, "AddedToFavoritesBtn", ".//div[@class='container-right-content']//*[@class='fv']/i[@class='i-heart-orange']", 30000, null, "7a5cb6ac-f4f6-476a-a151-6a504db89557");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddToFavoritesBtn item.
            /// </summary>
            [RepositoryItem("8171e99b-7f37-4cb1-af52-086de2980edf")]
            public virtual Ranorex.Unknown AddToFavoritesBtn
            {
                get
                {
                    return _addtofavoritesbtnInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AddToFavoritesBtn item info.
            /// </summary>
            [RepositoryItemInfo("8171e99b-7f37-4cb1-af52-086de2980edf")]
            public virtual RepoItemInfo AddToFavoritesBtnInfo
            {
                get
                {
                    return _addtofavoritesbtnInfo;
                }
            }

            /// <summary>
            /// The AddedToFavoritesBtn item.
            /// </summary>
            [RepositoryItem("7a5cb6ac-f4f6-476a-a151-6a504db89557")]
            public virtual Ranorex.ITag AddedToFavoritesBtn
            {
                get
                {
                    return _addedtofavoritesbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The AddedToFavoritesBtn item info.
            /// </summary>
            [RepositoryItemInfo("7a5cb6ac-f4f6-476a-a151-6a504db89557")]
            public virtual RepoItemInfo AddedToFavoritesBtnInfo
            {
                get
                {
                    return _addedtofavoritesbtnInfo;
                }
            }
        }

        /// <summary>
        /// The CartPageFolder folder.
        /// </summary>
        [RepositoryFolder("09e73355-0b29-4956-9394-895219e011eb")]
        public partial class CartPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pcheckboxtextInfo;
            RepoItemInfo _kaydetvedevametInfo;
            RepoItemInfo _oedemeyapInfo;

            /// <summary>
            /// Creates a new CartPage  folder.
            /// </summary>
            public CartPageFolder(RepoGenBaseFolder parentFolder) :
                    base("CartPage", "", parentFolder, 30000, null, false, "09e73355-0b29-4956-9394-895219e011eb", "")
            {
                _pcheckboxtextInfo = new RepoItemInfo(this, "PCheckboxText", ".//div[#'p-layout']/aside/div/div[2]/section//span", 30000, null, "d55e23da-dbdd-4421-937a-3cb34b09d962");
                _kaydetvedevametInfo = new RepoItemInfo(this, "KaydetVeDevamEt", ".//button[@innertext='Kaydet ve Devam Et']", 30000, null, "df87f721-3bd7-4788-841e-0141b997e9eb");
                _oedemeyapInfo = new RepoItemInfo(this, "OEdemeYap", ".//button[@innertext='Ödeme Yap']", 30000, null, "e4f650e4-66a3-4e03-a167-26525b497eeb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PCheckboxText item.
            /// </summary>
            [RepositoryItem("d55e23da-dbdd-4421-937a-3cb34b09d962")]
            public virtual Ranorex.SpanTag PCheckboxText
            {
                get
                {
                    return _pcheckboxtextInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PCheckboxText item info.
            /// </summary>
            [RepositoryItemInfo("d55e23da-dbdd-4421-937a-3cb34b09d962")]
            public virtual RepoItemInfo PCheckboxTextInfo
            {
                get
                {
                    return _pcheckboxtextInfo;
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item.
            /// </summary>
            [RepositoryItem("df87f721-3bd7-4788-841e-0141b997e9eb")]
            public virtual Ranorex.ButtonTag KaydetVeDevamEt
            {
                get
                {
                    return _kaydetvedevametInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item info.
            /// </summary>
            [RepositoryItemInfo("df87f721-3bd7-4788-841e-0141b997e9eb")]
            public virtual RepoItemInfo KaydetVeDevamEtInfo
            {
                get
                {
                    return _kaydetvedevametInfo;
                }
            }

            /// <summary>
            /// The OEdemeYap item.
            /// </summary>
            [RepositoryItem("e4f650e4-66a3-4e03-a167-26525b497eeb")]
            public virtual Ranorex.ButtonTag OEdemeYap
            {
                get
                {
                    return _oedemeyapInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The OEdemeYap item info.
            /// </summary>
            [RepositoryItemInfo("e4f650e4-66a3-4e03-a167-26525b497eeb")]
            public virtual RepoItemInfo OEdemeYapInfo
            {
                get
                {
                    return _oedemeyapInfo;
                }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("75057fdc-53fe-44a0-ac72-159d02765518")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginemailinputInfo;
            RepoItemInfo _loginpasswordinputInfo;
            RepoItemInfo _loginbtnInfo;
            RepoItemInfo _usernotloggedincontainerInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 30000, null, false, "75057fdc-53fe-44a0-ac72-159d02765518", "")
            {
                _loginemailinputInfo = new RepoItemInfo(this, "LoginEmailInput", ".//input[#'login-email']", 30000, null, "6f5e46d8-bfec-40db-8dec-831bd68382a4");
                _loginpasswordinputInfo = new RepoItemInfo(this, "LoginPasswordInput", ".//input[#'login-password-input']", 30000, null, "5636cfae-ee04-4b6d-8568-a3aa9efabb86");
                _loginbtnInfo = new RepoItemInfo(this, "LoginBtn", ".//form/*[@type='submit']", 30000, null, "6f2e0512-cb9a-4aee-ad77-2c7ca5d906cf");
                _usernotloggedincontainerInfo = new RepoItemInfo(this, "UserNotLoggedInContainer", ".//div[@class='user-notloggedin-container']", 30000, null, "fcb005b8-73ca-4121-9846-634fef9f40db");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginEmailInput item.
            /// </summary>
            [RepositoryItem("6f5e46d8-bfec-40db-8dec-831bd68382a4")]
            public virtual Ranorex.InputTag LoginEmailInput
            {
                get
                {
                    return _loginemailinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmailInput item info.
            /// </summary>
            [RepositoryItemInfo("6f5e46d8-bfec-40db-8dec-831bd68382a4")]
            public virtual RepoItemInfo LoginEmailInputInfo
            {
                get
                {
                    return _loginemailinputInfo;
                }
            }

            /// <summary>
            /// The LoginPasswordInput item.
            /// </summary>
            [RepositoryItem("5636cfae-ee04-4b6d-8568-a3aa9efabb86")]
            public virtual Ranorex.InputTag LoginPasswordInput
            {
                get
                {
                    return _loginpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("5636cfae-ee04-4b6d-8568-a3aa9efabb86")]
            public virtual RepoItemInfo LoginPasswordInputInfo
            {
                get
                {
                    return _loginpasswordinputInfo;
                }
            }

            /// <summary>
            /// The LoginBtn item.
            /// </summary>
            [RepositoryItem("6f2e0512-cb9a-4aee-ad77-2c7ca5d906cf")]
            public virtual Ranorex.Unknown LoginBtn
            {
                get
                {
                    return _loginbtnInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The LoginBtn item info.
            /// </summary>
            [RepositoryItemInfo("6f2e0512-cb9a-4aee-ad77-2c7ca5d906cf")]
            public virtual RepoItemInfo LoginBtnInfo
            {
                get
                {
                    return _loginbtnInfo;
                }
            }

            /// <summary>
            /// The UserNotLoggedInContainer item.
            /// </summary>
            [RepositoryItem("fcb005b8-73ca-4121-9846-634fef9f40db")]
            public virtual Ranorex.DivTag UserNotLoggedInContainer
            {
                get
                {
                    return _usernotloggedincontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UserNotLoggedInContainer item info.
            /// </summary>
            [RepositoryItemInfo("fcb005b8-73ca-4121-9846-634fef9f40db")]
            public virtual RepoItemInfo UserNotLoggedInContainerInfo
            {
                get
                {
                    return _usernotloggedincontainerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
