///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TrendyolTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("62222601-220c-44bf-a55a-74347c474ca6")]
    public partial class TrendyolTestRepository : RepoGenBaseFolder
    {
        static TrendyolTestRepository instance = new TrendyolTestRepository();
        TrendyolTestRepositoryFolders.TrendyolAppFolder _trendyol;
        TrendyolTestRepositoryFolders.ChromeAppFolder _chrome;

        /// <summary>
        /// Gets the singleton class instance representing the TrendyolTestRepository element repository.
        /// </summary>
        [RepositoryFolder("62222601-220c-44bf-a55a-74347c474ca6")]
        public static TrendyolTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TrendyolTestRepository() 
            : base("TrendyolTestRepository", "/", null, 0, false, "62222601-220c-44bf-a55a-74347c474ca6", ".\\RepositoryImages\\TrendyolTestRepository62222601.rximgres")
        {
            _trendyol = new TrendyolTestRepositoryFolders.TrendyolAppFolder(this);
            _chrome = new TrendyolTestRepositoryFolders.ChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("62222601-220c-44bf-a55a-74347c474ca6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The trendyol folder.
        /// </summary>
        [RepositoryFolder("20f41ba7-5a28-40ae-a06a-52591aa57649")]
        public virtual TrendyolTestRepositoryFolders.TrendyolAppFolder trendyol
        {
            get { return _trendyol; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
        public virtual TrendyolTestRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TrendyolTestRepositoryFolders
    {
        /// <summary>
        /// The TrendyolAppFolder folder.
        /// </summary>
        [RepositoryFolder("20f41ba7-5a28-40ae-a06a-52591aa57649")]
        public partial class TrendyolAppFolder : RepoGenBaseFolder
        {
            TrendyolTestRepositoryFolders.RegisterPageFolder _registerpage;
            TrendyolTestRepositoryFolders.ProductDetailsFolder _productdetails;
            TrendyolTestRepositoryFolders.MyFavoritesPageFolder _myfavoritespage;
            TrendyolTestRepositoryFolders.CartPageFolder _cartpage;
            TrendyolTestRepositoryFolders.LoginPageFolder _loginpage;
            RepoItemInfo _myaccountInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _marketingemailcheckboxdivInfo;
            RepoItemInfo _personaldatacheckboxdivInfo;
            RepoItemInfo _errorboxwrapperInfo;
            RepoItemInfo _spantagkuepşekersargılı750gr869038Info;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _irmakkuepşekersargılı750grInfo;
            RepoItemInfo _trendyolInfo;
            RepoItemInfo _sepetionaylaInfo;
            RepoItemInfo _userloggedincontainerInfo;
            RepoItemInfo _myfavoritesInfo;
            RepoItemInfo _logoutbuttonInfo;
            RepoItemInfo _girisyapbtnInfo;

            /// <summary>
            /// Creates a new trendyol  folder.
            /// </summary>
            public TrendyolAppFolder(RepoGenBaseFolder parentFolder) :
                    base("trendyol", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "20f41ba7-5a28-40ae-a06a-52591aa57649", "")
            {
                _registerpage = new TrendyolTestRepositoryFolders.RegisterPageFolder(this);
                _productdetails = new TrendyolTestRepositoryFolders.ProductDetailsFolder(this);
                _myfavoritespage = new TrendyolTestRepositoryFolders.MyFavoritesPageFolder(this);
                _cartpage = new TrendyolTestRepositoryFolders.CartPageFolder(this);
                _loginpage = new TrendyolTestRepositoryFolders.LoginPageFolder(this);
                _myaccountInfo = new RepoItemInfo(this, "MyAccount", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Hesabım']", ".//div[#'account-navigation-container']//p[@innertext='Hesabım']", 30000, null, "369d8fde-4a96-4044-8a94-e0cc4df031c1");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "85df90b8-1a3b-4517-a07b-f17096ccda49");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "7556e76c-f236-4a6a-bc49-bfbee4e070b1");
                _marketingemailcheckboxdivInfo = new RepoItemInfo(this, "MarketingEmailCheckboxDiv", ".//div[@name='marketing-email']", ".//div[#'login-register']//form/div[5]/div/div[1]/div/div", 30000, null, "e3abd9cc-54b9-45a1-9bf9-141a9ab18028");
                _personaldatacheckboxdivInfo = new RepoItemInfo(this, "PersonalDataCheckboxDiv", ".//div[@name='personal-data-error']", ".//div[#'login-register']//form/div[5]/div/div[1]/div/div", 30000, null, "3f4881b2-5705-49f0-bf25-38d7b2d1244a");
                _errorboxwrapperInfo = new RepoItemInfo(this, "ErrorBoxWrapper", ".//div[#'error-box-wrapper']", ".//div[#'error-box-wrapper']", 30000, null, "2bbe84ec-347e-4ad4-9eca-b0126a57744f");
                _spantagkuepşekersargılı750gr869038Info = new RepoItemInfo(this, "SpanTagKuepŞekerSargılı750Gr869038", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[1]/div/div/div[1]/h1[@innertext='Irmak']/span[@innertext>' Küp Şeker Sargılı 750 gr']", ".//main[#'product-detail-app']//span[@innertext>' Küp Şeker Sargılı 750 gr']", 30000, null, "3a59b7a8-5933-4e2d-a248-18965ace6953");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[5]/button/div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "145f3143-f3e4-4cf9-9a65-31ce6beb267b");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "30140022-9b65-4374-84e9-c4f939a146bc");
                _irmakkuepşekersargılı750grInfo = new RepoItemInfo(this, "IrmakKuepŞekerSargılı750Gr", ".//div[#'pb-container']//a[@href>'https://www.trendyol.com/']/p[@title>'Irmak Küp Şeker Sargılı 750']", ".//div[#'pb-container']//p[@title>'Irmak Küp Şeker Sargılı 750']", 30000, null, "03974d67-9ef6-4d6f-b162-6d64eb337953");
                _trendyolInfo = new RepoItemInfo(this, "Trendyol", ".//a[#'logo']/img[@alt='Trendyol']", ".//a[#'logo']/img[@alt='Trendyol']", 30000, null, "c089645d-6d46-4109-83b5-19196ab5a78f");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//div[#'pb-container']/aside/div/div[1]/?/?/span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']//span[@innertext='Sepeti Onayla']", 30000, null, "87145e4a-8258-4631-8aa9-bd75ad265f70");
                _userloggedincontainerInfo = new RepoItemInfo(this, "UserLoggedinContainer", ".//div[#'account-navigation-container']", ".//div[#'account-navigation-container']/div/div[1]/div[2]/div", 30000, null, "6e8f84c7-5e18-4e3c-b702-bb202e7edb1f");
                _myfavoritesInfo = new RepoItemInfo(this, "MyFavorites", "a[@href='/Hesabim/Favoriler']", "element", 30000, null, "29496650-d784-4492-9dce-b55377b1866f");
                _logoutbuttonInfo = new RepoItemInfo(this, "LogoutButton", ".//div[#'account-navigation-container']/div/div[1]//button/p[@innertext='Çıkış Yap']", ".//div[#'account-navigation-container']//p[@innertext='Çıkış Yap']", 30000, null, "ec3932f7-c41f-4335-b62f-4cbf1a883e25");
                _girisyapbtnInfo = new RepoItemInfo(this, "GirisYapBtn", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "0df4785a-ac50-4cae-b7a6-27d02e1ae95c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("20f41ba7-5a28-40ae-a06a-52591aa57649")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("20f41ba7-5a28-40ae-a06a-52591aa57649")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyAccount item.
            /// </summary>
            [RepositoryItem("369d8fde-4a96-4044-8a94-e0cc4df031c1")]
            public virtual Ranorex.PTag MyAccount
            {
                get
                {
                    return _myaccountInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MyAccount item info.
            /// </summary>
            [RepositoryItemInfo("369d8fde-4a96-4044-8a94-e0cc4df031c1")]
            public virtual RepoItemInfo MyAccountInfo
            {
                get
                {
                    return _myaccountInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("85df90b8-1a3b-4517-a07b-f17096ccda49")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("85df90b8-1a3b-4517-a07b-f17096ccda49")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("7556e76c-f236-4a6a-bc49-bfbee4e070b1")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("7556e76c-f236-4a6a-bc49-bfbee4e070b1")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The MarketingEmailCheckboxDiv item.
            /// </summary>
            [RepositoryItem("e3abd9cc-54b9-45a1-9bf9-141a9ab18028")]
            public virtual Ranorex.DivTag MarketingEmailCheckboxDiv
            {
                get
                {
                    return _marketingemailcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MarketingEmailCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("e3abd9cc-54b9-45a1-9bf9-141a9ab18028")]
            public virtual RepoItemInfo MarketingEmailCheckboxDivInfo
            {
                get
                {
                    return _marketingemailcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The PersonalDataCheckboxDiv item.
            /// </summary>
            [RepositoryItem("3f4881b2-5705-49f0-bf25-38d7b2d1244a")]
            public virtual Ranorex.DivTag PersonalDataCheckboxDiv
            {
                get
                {
                    return _personaldatacheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalDataCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("3f4881b2-5705-49f0-bf25-38d7b2d1244a")]
            public virtual RepoItemInfo PersonalDataCheckboxDivInfo
            {
                get
                {
                    return _personaldatacheckboxdivInfo;
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item.
            /// </summary>
            [RepositoryItem("2bbe84ec-347e-4ad4-9eca-b0126a57744f")]
            public virtual Ranorex.DivTag ErrorBoxWrapper
            {
                get
                {
                    return _errorboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item info.
            /// </summary>
            [RepositoryItemInfo("2bbe84ec-347e-4ad4-9eca-b0126a57744f")]
            public virtual RepoItemInfo ErrorBoxWrapperInfo
            {
                get
                {
                    return _errorboxwrapperInfo;
                }
            }

            /// <summary>
            /// The SpanTagKuepŞekerSargılı750Gr869038 item.
            /// </summary>
            [RepositoryItem("3a59b7a8-5933-4e2d-a248-18965ace6953")]
            public virtual Ranorex.SpanTag SpanTagKuepŞekerSargılı750Gr869038
            {
                get
                {
                    return _spantagkuepşekersargılı750gr869038Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagKuepŞekerSargılı750Gr869038 item info.
            /// </summary>
            [RepositoryItemInfo("3a59b7a8-5933-4e2d-a248-18965ace6953")]
            public virtual RepoItemInfo SpanTagKuepŞekerSargılı750Gr869038Info
            {
                get
                {
                    return _spantagkuepşekersargılı750gr869038Info;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("145f3143-f3e4-4cf9-9a65-31ce6beb267b")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("145f3143-f3e4-4cf9-9a65-31ce6beb267b")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("30140022-9b65-4374-84e9-c4f939a146bc")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("30140022-9b65-4374-84e9-c4f939a146bc")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The IrmakKuepŞekerSargılı750Gr item.
            /// </summary>
            [RepositoryItem("03974d67-9ef6-4d6f-b162-6d64eb337953")]
            public virtual Ranorex.PTag IrmakKuepŞekerSargılı750Gr
            {
                get
                {
                    return _irmakkuepşekersargılı750grInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IrmakKuepŞekerSargılı750Gr item info.
            /// </summary>
            [RepositoryItemInfo("03974d67-9ef6-4d6f-b162-6d64eb337953")]
            public virtual RepoItemInfo IrmakKuepŞekerSargılı750GrInfo
            {
                get
                {
                    return _irmakkuepşekersargılı750grInfo;
                }
            }

            /// <summary>
            /// The Trendyol item.
            /// </summary>
            [RepositoryItem("c089645d-6d46-4109-83b5-19196ab5a78f")]
            public virtual Ranorex.ImgTag Trendyol
            {
                get
                {
                    return _trendyolInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Trendyol item info.
            /// </summary>
            [RepositoryItemInfo("c089645d-6d46-4109-83b5-19196ab5a78f")]
            public virtual RepoItemInfo TrendyolInfo
            {
                get
                {
                    return _trendyolInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("87145e4a-8258-4631-8aa9-bd75ad265f70")]
            public virtual Ranorex.SpanTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("87145e4a-8258-4631-8aa9-bd75ad265f70")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The UserLoggedinContainer item.
            /// </summary>
            [RepositoryItem("6e8f84c7-5e18-4e3c-b702-bb202e7edb1f")]
            public virtual Ranorex.DivTag UserLoggedinContainer
            {
                get
                {
                    return _userloggedincontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UserLoggedinContainer item info.
            /// </summary>
            [RepositoryItemInfo("6e8f84c7-5e18-4e3c-b702-bb202e7edb1f")]
            public virtual RepoItemInfo UserLoggedinContainerInfo
            {
                get
                {
                    return _userloggedincontainerInfo;
                }
            }

            /// <summary>
            /// The MyFavorites item.
            /// </summary>
            [RepositoryItem("29496650-d784-4492-9dce-b55377b1866f")]
            public virtual Ranorex.ATag MyFavorites
            {
                get
                {
                    return _myfavoritesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MyFavorites item info.
            /// </summary>
            [RepositoryItemInfo("29496650-d784-4492-9dce-b55377b1866f")]
            public virtual RepoItemInfo MyFavoritesInfo
            {
                get
                {
                    return _myfavoritesInfo;
                }
            }

            /// <summary>
            /// The LogoutButton item.
            /// </summary>
            [RepositoryItem("ec3932f7-c41f-4335-b62f-4cbf1a883e25")]
            public virtual Ranorex.PTag LogoutButton
            {
                get
                {
                    return _logoutbuttonInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The LogoutButton item info.
            /// </summary>
            [RepositoryItemInfo("ec3932f7-c41f-4335-b62f-4cbf1a883e25")]
            public virtual RepoItemInfo LogoutButtonInfo
            {
                get
                {
                    return _logoutbuttonInfo;
                }
            }

            /// <summary>
            /// The GirisYapBtn item.
            /// </summary>
            [RepositoryItem("0df4785a-ac50-4cae-b7a6-27d02e1ae95c")]
            public virtual Ranorex.PTag GirisYapBtn
            {
                get
                {
                    return _girisyapbtnInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirisYapBtn item info.
            /// </summary>
            [RepositoryItemInfo("0df4785a-ac50-4cae-b7a6-27d02e1ae95c")]
            public virtual RepoItemInfo GirisYapBtnInfo
            {
                get
                {
                    return _girisyapbtnInfo;
                }
            }

            /// <summary>
            /// The RegisterPage folder.
            /// </summary>
            [RepositoryFolder("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual TrendyolTestRepositoryFolders.RegisterPageFolder RegisterPage
            {
                get { return _registerpage; }
            }

            /// <summary>
            /// The ProductDetails folder.
            /// </summary>
            [RepositoryFolder("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual TrendyolTestRepositoryFolders.ProductDetailsFolder ProductDetails
            {
                get { return _productdetails; }
            }

            /// <summary>
            /// The MyFavoritesPage folder.
            /// </summary>
            [RepositoryFolder("d46cc1fe-5ca7-42c2-a6d7-39bda40200d6")]
            public virtual TrendyolTestRepositoryFolders.MyFavoritesPageFolder MyFavoritesPage
            {
                get { return _myfavoritespage; }
            }

            /// <summary>
            /// The CartPage folder.
            /// </summary>
            [RepositoryFolder("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual TrendyolTestRepositoryFolders.CartPageFolder CartPage
            {
                get { return _cartpage; }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual TrendyolTestRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }
        }

        /// <summary>
        /// The RegisterPageFolder folder.
        /// </summary>
        [RepositoryFolder("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
        public partial class RegisterPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _personalcheckboxdivInfo;
            RepoItemInfo _marketingcheckboxdivInfo;
            RepoItemInfo _registerbuttonInfo;
            RepoItemInfo _favorilerimInfo;
            RepoItemInfo _kuepşekersargılı750grInfo;

            /// <summary>
            /// Creates a new RegisterPage  folder.
            /// </summary>
            public RegisterPageFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterPage", "", parentFolder, 30000, null, false, "92ff70e5-3c16-4368-8ec6-a1252c5236f8", "")
            {
                _personalcheckboxdivInfo = new RepoItemInfo(this, "PersonalCheckboxDiv", ".//div[@class='personal-checkbox']", ".//div[#'login-register']//form/div[6]/div/div[1]", 30000, null, "49e66d49-8381-4708-a1a0-fe36dc994057");
                _marketingcheckboxdivInfo = new RepoItemInfo(this, "MarketingCheckboxDiv", ".//div[@class='marketing-checkbox']", ".//div[#'login-register']//form/div[5]/div/div[1]", 30000, null, "cb1d2aaf-e139-4612-b6b1-c9311b50efc6");
                _registerbuttonInfo = new RepoItemInfo(this, "RegisterButton", ".//form/button", ".//div[#'login-register']//form/button", 30000, null, "ea0e4a66-6c0b-4f1a-b677-e867cd149887");
                _favorilerimInfo = new RepoItemInfo(this, "Favorilerim", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "3195a5c9-449f-408d-8614-5a131ace07b5");
                _kuepşekersargılı750grInfo = new RepoItemInfo(this, "KuepŞekerSargılı750Gr", ".//div[#'account-gw-favorites']/div/div[3]/div/div[1]/a[@href>'https://www.trendyol.com/']//span[@title='Küp Şeker Sargılı 750 gr']", ".//div[#'account-gw-favorites']//span[@title='Küp Şeker Sargılı 750 gr']", 30000, null, "b27716f6-b8df-4297-aa2d-c2955671c4df");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PersonalCheckboxDiv item.
            /// </summary>
            [RepositoryItem("49e66d49-8381-4708-a1a0-fe36dc994057")]
            public virtual Ranorex.DivTag PersonalCheckboxDiv
            {
                get
                {
                    return _personalcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("49e66d49-8381-4708-a1a0-fe36dc994057")]
            public virtual RepoItemInfo PersonalCheckboxDivInfo
            {
                get
                {
                    return _personalcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The MarketingCheckboxDiv item.
            /// </summary>
            [RepositoryItem("cb1d2aaf-e139-4612-b6b1-c9311b50efc6")]
            public virtual Ranorex.DivTag MarketingCheckboxDiv
            {
                get
                {
                    return _marketingcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MarketingCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("cb1d2aaf-e139-4612-b6b1-c9311b50efc6")]
            public virtual RepoItemInfo MarketingCheckboxDivInfo
            {
                get
                {
                    return _marketingcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The RegisterButton item.
            /// </summary>
            [RepositoryItem("ea0e4a66-6c0b-4f1a-b677-e867cd149887")]
            public virtual Ranorex.ButtonTag RegisterButton
            {
                get
                {
                    return _registerbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RegisterButton item info.
            /// </summary>
            [RepositoryItemInfo("ea0e4a66-6c0b-4f1a-b677-e867cd149887")]
            public virtual RepoItemInfo RegisterButtonInfo
            {
                get
                {
                    return _registerbuttonInfo;
                }
            }

            /// <summary>
            /// The Favorilerim item.
            /// </summary>
            [RepositoryItem("3195a5c9-449f-408d-8614-5a131ace07b5")]
            public virtual Ranorex.PTag Favorilerim
            {
                get
                {
                    return _favorilerimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Favorilerim item info.
            /// </summary>
            [RepositoryItemInfo("3195a5c9-449f-408d-8614-5a131ace07b5")]
            public virtual RepoItemInfo FavorilerimInfo
            {
                get
                {
                    return _favorilerimInfo;
                }
            }

            /// <summary>
            /// The KuepŞekerSargılı750Gr item.
            /// </summary>
            [RepositoryItem("b27716f6-b8df-4297-aa2d-c2955671c4df")]
            public virtual Ranorex.SpanTag KuepŞekerSargılı750Gr
            {
                get
                {
                    return _kuepşekersargılı750grInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The KuepŞekerSargılı750Gr item info.
            /// </summary>
            [RepositoryItemInfo("b27716f6-b8df-4297-aa2d-c2955671c4df")]
            public virtual RepoItemInfo KuepŞekerSargılı750GrInfo
            {
                get
                {
                    return _kuepşekersargılı750grInfo;
                }
            }
        }

        /// <summary>
        /// The ProductDetailsFolder folder.
        /// </summary>
        [RepositoryFolder("27698d01-8ea9-4b65-9edd-3224afe26aef")]
        public partial class ProductDetailsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addtofavoritesbtnInfo;
            RepoItemInfo _heart_icon_fullInfo;

            /// <summary>
            /// Creates a new ProductDetails  folder.
            /// </summary>
            public ProductDetailsFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductDetails", "", parentFolder, 30000, null, false, "27698d01-8ea9-4b65-9edd-3224afe26aef", "")
            {
                _addtofavoritesbtnInfo = new RepoItemInfo(this, "AddToFavoritesBtn", ".//div[@class='container-right-content']//button[@class='fv']", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[5]/div/div/div[1]/button", 30000, null, "8171e99b-7f37-4cb1-af52-086de2980edf");
                _heart_icon_fullInfo = new RepoItemInfo(this, "heart_icon_full", ".//div[@class='favorite-button']/button[@class='fv']/i[@class='i-hearth-orange']", "element", 30000, null, "663042a2-a6e4-406c-af1a-87f759da0c78");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddToFavoritesBtn item.
            /// </summary>
            [RepositoryItem("8171e99b-7f37-4cb1-af52-086de2980edf")]
            public virtual Ranorex.ButtonTag AddToFavoritesBtn
            {
                get
                {
                    return _addtofavoritesbtnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToFavoritesBtn item info.
            /// </summary>
            [RepositoryItemInfo("8171e99b-7f37-4cb1-af52-086de2980edf")]
            public virtual RepoItemInfo AddToFavoritesBtnInfo
            {
                get
                {
                    return _addtofavoritesbtnInfo;
                }
            }

            /// <summary>
            /// The heart_icon_full item.
            /// </summary>
            [RepositoryItem("663042a2-a6e4-406c-af1a-87f759da0c78")]
            public virtual Ranorex.ITag heart_icon_full
            {
                get
                {
                    return _heart_icon_fullInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The heart_icon_full item info.
            /// </summary>
            [RepositoryItemInfo("663042a2-a6e4-406c-af1a-87f759da0c78")]
            public virtual RepoItemInfo heart_icon_fullInfo
            {
                get
                {
                    return _heart_icon_fullInfo;
                }
            }
        }

        /// <summary>
        /// The MyFavoritesPageFolder folder.
        /// </summary>
        [RepositoryFolder("d46cc1fe-5ca7-42c2-a6d7-39bda40200d6")]
        public partial class MyFavoritesPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _favoriteproductscontainerInfo;

            /// <summary>
            /// Creates a new MyFavoritesPage  folder.
            /// </summary>
            public MyFavoritesPageFolder(RepoGenBaseFolder parentFolder) :
                    base("MyFavoritesPage", "", parentFolder, 30000, null, false, "d46cc1fe-5ca7-42c2-a6d7-39bda40200d6", "")
            {
                _favoriteproductscontainerInfo = new RepoItemInfo(this, "FavoriteProductsContainer", ".//div[@class='favored-product-container']", "element", 30000, null, "30521293-b3ba-48e7-b411-7bd795461d33");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d46cc1fe-5ca7-42c2-a6d7-39bda40200d6")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d46cc1fe-5ca7-42c2-a6d7-39bda40200d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FavoriteProductsContainer item.
            /// </summary>
            [RepositoryItem("30521293-b3ba-48e7-b411-7bd795461d33")]
            public virtual Ranorex.DivTag FavoriteProductsContainer
            {
                get
                {
                    return _favoriteproductscontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FavoriteProductsContainer item info.
            /// </summary>
            [RepositoryItemInfo("30521293-b3ba-48e7-b411-7bd795461d33")]
            public virtual RepoItemInfo FavoriteProductsContainerInfo
            {
                get
                {
                    return _favoriteproductscontainerInfo;
                }
            }
        }

        /// <summary>
        /// The CartPageFolder folder.
        /// </summary>
        [RepositoryFolder("09e73355-0b29-4956-9394-895219e011eb")]
        public partial class CartPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pcheckboxtextInfo;
            RepoItemInfo _kaydetvedevametInfo;
            RepoItemInfo _oedemeyapInfo;

            /// <summary>
            /// Creates a new CartPage  folder.
            /// </summary>
            public CartPageFolder(RepoGenBaseFolder parentFolder) :
                    base("CartPage", "", parentFolder, 30000, null, false, "09e73355-0b29-4956-9394-895219e011eb", "")
            {
                _pcheckboxtextInfo = new RepoItemInfo(this, "PCheckboxText", ".//div[#'p-layout']/aside/div/div[2]/section//span", ".//div[#'p-layout']/aside/div/div[2]/section/div/label/span", 30000, null, "d55e23da-dbdd-4421-937a-3cb34b09d962");
                _kaydetvedevametInfo = new RepoItemInfo(this, "KaydetVeDevamEt", ".//button[@innertext='Kaydet ve Devam Et']", ".//div[#'p-layout']//button[@innertext='Kaydet ve Devam Et']", 30000, null, "df87f721-3bd7-4788-841e-0141b997e9eb");
                _oedemeyapInfo = new RepoItemInfo(this, "OEdemeYap", ".//button[@innertext='Ödeme Yap']", ".//div[#'p-layout']//button[@innertext='Ödeme Yap']", 30000, null, "e4f650e4-66a3-4e03-a167-26525b497eeb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PCheckboxText item.
            /// </summary>
            [RepositoryItem("d55e23da-dbdd-4421-937a-3cb34b09d962")]
            public virtual Ranorex.SpanTag PCheckboxText
            {
                get
                {
                    return _pcheckboxtextInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PCheckboxText item info.
            /// </summary>
            [RepositoryItemInfo("d55e23da-dbdd-4421-937a-3cb34b09d962")]
            public virtual RepoItemInfo PCheckboxTextInfo
            {
                get
                {
                    return _pcheckboxtextInfo;
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item.
            /// </summary>
            [RepositoryItem("df87f721-3bd7-4788-841e-0141b997e9eb")]
            public virtual Ranorex.ButtonTag KaydetVeDevamEt
            {
                get
                {
                    return _kaydetvedevametInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item info.
            /// </summary>
            [RepositoryItemInfo("df87f721-3bd7-4788-841e-0141b997e9eb")]
            public virtual RepoItemInfo KaydetVeDevamEtInfo
            {
                get
                {
                    return _kaydetvedevametInfo;
                }
            }

            /// <summary>
            /// The OEdemeYap item.
            /// </summary>
            [RepositoryItem("e4f650e4-66a3-4e03-a167-26525b497eeb")]
            public virtual Ranorex.ButtonTag OEdemeYap
            {
                get
                {
                    return _oedemeyapInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The OEdemeYap item info.
            /// </summary>
            [RepositoryItemInfo("e4f650e4-66a3-4e03-a167-26525b497eeb")]
            public virtual RepoItemInfo OEdemeYapInfo
            {
                get
                {
                    return _oedemeyapInfo;
                }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("75057fdc-53fe-44a0-ac72-159d02765518")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginpasswordinputInfo;
            RepoItemInfo _loginemailInfo;
            RepoItemInfo _loginbuttonInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 30000, null, false, "75057fdc-53fe-44a0-ac72-159d02765518", "")
            {
                _loginpasswordinputInfo = new RepoItemInfo(this, "LoginPasswordInput", ".//input[#'login-password-input']", ".//input[#'login-password-input']", 30000, null, "5636cfae-ee04-4b6d-8568-a3aa9efabb86");
                _loginemailInfo = new RepoItemInfo(this, "LoginEmail", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "6f5e46d8-bfec-40db-8dec-831bd68382a4");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//form/button", ".//div[#'login-register']//form/button/span[@innertext='Giriş Yap']", 30000, null, "998acbc8-a2bb-490b-b287-ed89a4098891");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPasswordInput item.
            /// </summary>
            [RepositoryItem("5636cfae-ee04-4b6d-8568-a3aa9efabb86")]
            public virtual Ranorex.InputTag LoginPasswordInput
            {
                get
                {
                    return _loginpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("5636cfae-ee04-4b6d-8568-a3aa9efabb86")]
            public virtual RepoItemInfo LoginPasswordInputInfo
            {
                get
                {
                    return _loginpasswordinputInfo;
                }
            }

            /// <summary>
            /// The LoginEmail item.
            /// </summary>
            [RepositoryItem("6f5e46d8-bfec-40db-8dec-831bd68382a4")]
            public virtual Ranorex.InputTag LoginEmail
            {
                get
                {
                    return _loginemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmail item info.
            /// </summary>
            [RepositoryItemInfo("6f5e46d8-bfec-40db-8dec-831bd68382a4")]
            public virtual RepoItemInfo LoginEmailInfo
            {
                get
                {
                    return _loginemailInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("998acbc8-a2bb-490b-b287-ed89a4098891")]
            public virtual Ranorex.Button LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("998acbc8-a2bb-490b-b287-ed89a4098891")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pane1Info;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form", parentFolder, 30000, null, true, "f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c", "")
            {
                _pane1Info = new RepoItemInfo(this, "Pane1", "container[@accessiblename='Google Chrome']/container/container[2]/container[1]", "?/?/container[@accessiblename='Google Chrome']/container[@accessiblerole='Pane']/container[2]/container[1]", 30000, null, "b447615b-869c-47fd-8d1e-44cbd91ce23c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane1 item.
            /// </summary>
            [RepositoryItem("b447615b-869c-47fd-8d1e-44cbd91ce23c")]
            public virtual Ranorex.Container Pane1
            {
                get
                {
                    return _pane1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane1 item info.
            /// </summary>
            [RepositoryItemInfo("b447615b-869c-47fd-8d1e-44cbd91ce23c")]
            public virtual RepoItemInfo Pane1Info
            {
                get
                {
                    return _pane1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
