///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TrendyolTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TrendyolTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("62222601-220c-44bf-a55a-74347c474ca6")]
    public partial class TrendyolTestRepository : RepoGenBaseFolder
    {
        static TrendyolTestRepository instance = new TrendyolTestRepository();
        TrendyolTestRepositoryFolders.TrendyolAppFolder _trendyol;
        TrendyolTestRepositoryFolders.ChromeAppFolder _chrome;
        RepoItemInfo _errorboxwrapperInfo;

        /// <summary>
        /// Gets the singleton class instance representing the TrendyolTestRepository element repository.
        /// </summary>
        [RepositoryFolder("62222601-220c-44bf-a55a-74347c474ca6")]
        public static TrendyolTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TrendyolTestRepository() 
            : base("TrendyolTestRepository", "/", null, 0, false, "62222601-220c-44bf-a55a-74347c474ca6", ".\\RepositoryImages\\TrendyolTestRepository62222601.rximgres")
        {
            _trendyol = new TrendyolTestRepositoryFolders.TrendyolAppFolder(this);
            _chrome = new TrendyolTestRepositoryFolders.ChromeAppFolder(this);
            _errorboxwrapperInfo = new RepoItemInfo(this, "ErrorBoxWrapper", "/dom[@domain='www.trendyol.com']//div[#'error-box-wrapper']", 30000, null, "2bbe84ec-347e-4ad4-9eca-b0126a57744f");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("62222601-220c-44bf-a55a-74347c474ca6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ErrorBoxWrapper item.
        /// </summary>
        [RepositoryItem("2bbe84ec-347e-4ad4-9eca-b0126a57744f")]
        public virtual Ranorex.DivTag ErrorBoxWrapper
        {
            get
            {
                 return _errorboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
            }
        }

        /// <summary>
        /// The ErrorBoxWrapper item info.
        /// </summary>
        [RepositoryItemInfo("2bbe84ec-347e-4ad4-9eca-b0126a57744f")]
        public virtual RepoItemInfo ErrorBoxWrapperInfo
        {
            get
            {
                return _errorboxwrapperInfo;
            }
        }

        /// <summary>
        /// The trendyol folder.
        /// </summary>
        [RepositoryFolder("20f41ba7-5a28-40ae-a06a-52591aa57649")]
        public virtual TrendyolTestRepositoryFolders.TrendyolAppFolder trendyol
        {
            get { return _trendyol; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
        public virtual TrendyolTestRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TrendyolTestRepositoryFolders
    {
        /// <summary>
        /// The TrendyolAppFolder folder.
        /// </summary>
        [RepositoryFolder("20f41ba7-5a28-40ae-a06a-52591aa57649")]
        public partial class TrendyolAppFolder : RepoGenBaseFolder
        {
            TrendyolTestRepositoryFolders.RegisterPageFolder _registerpage;
            TrendyolTestRepositoryFolders.ProductDetailsFolder _productdetails;
            TrendyolTestRepositoryFolders.CartPageFolder _cartpage;
            TrendyolTestRepositoryFolders.LoginPageFolder _loginpage;
            RepoItemInfo _marketingemailcheckboxdivInfo;
            RepoItemInfo _personaldatacheckboxdivInfo;
            RepoItemInfo _addtocartbuttonInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _proceedtocheckoutbuttonInfo;
            RepoItemInfo _searchinputInfo;
            RepoItemInfo _logoutbuttonInfo;
            MyAccountButtonInfoClass _myaccountbuttonInfo;
            RepoItemInfo _firstproductnameinsearchInfo;
            RepoItemInfo _productnamespanInfo;
            RepoItemInfo _productnamecartpageInfo;
            RepoItemInfo _registeremailinputInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _usernotloggedincontainerInfo;
            RepoItemInfo _firstproductlinkinsearchpageInfo;
            RepoItemInfo _firstproductlinkincartpageInfo;

            /// <summary>
            /// Creates a new trendyol  folder.
            /// </summary>
            public TrendyolAppFolder(RepoGenBaseFolder parentFolder) :
                    base("trendyol", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "20f41ba7-5a28-40ae-a06a-52591aa57649", "")
            {
                _registerpage = new TrendyolTestRepositoryFolders.RegisterPageFolder(this);
                _productdetails = new TrendyolTestRepositoryFolders.ProductDetailsFolder(this);
                _cartpage = new TrendyolTestRepositoryFolders.CartPageFolder(this);
                _loginpage = new TrendyolTestRepositoryFolders.LoginPageFolder(this);
                _marketingemailcheckboxdivInfo = new RepoItemInfo(this, "MarketingEmailCheckboxDiv", ".//div[@name='marketing-email']", ".//div[#'login-register']//form/div[5]/div/div[1]/div/div", 30000, null, "e3abd9cc-54b9-45a1-9bf9-141a9ab18028");
                _personaldatacheckboxdivInfo = new RepoItemInfo(this, "PersonalDataCheckboxDiv", ".//div[@name='personal-data-error']", ".//div[#'login-register']//form/div[5]/div/div[1]/div/div", 30000, null, "3f4881b2-5705-49f0-bf25-38d7b2d1244a");
                _addtocartbuttonInfo = new RepoItemInfo(this, "AddToCartButton", ".//button[@class='add-to-basket']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "145f3143-f3e4-4cf9-9a65-31ce6beb267b");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "30140022-9b65-4374-84e9-c4f939a146bc");
                _proceedtocheckoutbuttonInfo = new RepoItemInfo(this, "ProceedToCheckoutButton", ".//span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']//span[@innertext='Sepeti Onayla']", 30000, null, "87145e4a-8258-4631-8aa9-bd75ad265f70");
                _searchinputInfo = new RepoItemInfo(this, "SearchInput", ".//div[@id='sfx-discovery-search-suggestions']//input", ".//div[#'sfx-discovery-search-suggestions']//input[@type='text']", 30000, null, "9802ff52-3124-481d-8de5-384343e9aa44");
                _logoutbuttonInfo = new RepoItemInfo(this, "LogoutButton", ".//button[@class='loggedin-account-item']", "", 30000, null, "ec3932f7-c41f-4335-b62f-4cbf1a883e25");
                _myaccountbuttonInfo = new MyAccountButtonInfoClass(this);
                _firstproductnameinsearchInfo = new RepoItemInfo(this, "FirstProductNameInSearch", ".//div[@class~'prdct-desc-cntnr'][1]", "element", 30000, null, "8a0628f8-34df-46d8-94ae-7ee4d756d0b0");
                _productnamespanInfo = new RepoItemInfo(this, "ProductNameSpan", ".//h1[@class='pr-new-br']/span", "", 30000, null, "9ab1077c-422a-444a-8fe4-6eeca5d38214");
                _productnamecartpageInfo = new RepoItemInfo(this, "ProductNameCartPage", ".//p[@class='pb-item'][1]", "element", 30000, null, "3ce6aebc-722b-4549-ad7c-5bd29b78943f");
                _registeremailinputInfo = new RepoItemInfo(this, "RegisterEmailInput", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "85df90b8-1a3b-4517-a07b-f17096ccda49");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "7556e76c-f236-4a6a-bc49-bfbee4e070b1");
                _usernotloggedincontainerInfo = new RepoItemInfo(this, "UserNotLoggedInContainer", ".//div[@class='user-notloggedin-container']", "element", 30000, null, "fcb005b8-73ca-4121-9846-634fef9f40db");
                _firstproductlinkinsearchpageInfo = new RepoItemInfo(this, "FirstProductLinkInSearchPage", ".//div[@class~'p-card-chldrn-cntnr card-border']/a", "", 30000, null, "cc9739c1-2ad2-49e2-8513-9477a7a6bbdb");
                _firstproductlinkincartpageInfo = new RepoItemInfo(this, "FirstProductLinkInCartPage", ".//div[@class='pb-basket-item']/a", "", 30000, null, "562e393f-d3ee-4c03-8464-d3d86e336eaf");
            }

            /// <summary>
            /// The MyAccountButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("7c14b9ca-221d-4a87-8076-2e1f24a83769")]
            public class MyAccountButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// MyAccountButtonInfoClass class constructor.
                /// </summary>
                public MyAccountButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "MyAccountButton", ".//p[text()~'Hesabım']", 30000, null, "7c14b9ca-221d-4a87-8076-2e1f24a83769")
                { }

                /// <summary>
                /// Gets the MyAccountButtonScreenshot item image.
                /// </summary>
                /// <returns>The MyAccountButtonScreenshot image.</returns>
                [RepositoryImage("5922e6a8-f452-4613-ae43-0d40fd4da345")]
                public CompressedImage GetMyAccountButtonScreenshot()
                {
                    return GetImage("5922e6a8-f452-4613-ae43-0d40fd4da345");
                }

                /// <summary>
                /// Gets the MyAccountButtonScreenshot item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5922e6a8-f452-4613-ae43-0d40fd4da345")]
                public CompressedImage GetMyAccountButtonScreenshot(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5922e6a8-f452-4613-ae43-0d40fd4da345", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("20f41ba7-5a28-40ae-a06a-52591aa57649")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("20f41ba7-5a28-40ae-a06a-52591aa57649")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MarketingEmailCheckboxDiv item.
            /// </summary>
            [RepositoryItem("e3abd9cc-54b9-45a1-9bf9-141a9ab18028")]
            public virtual Ranorex.DivTag MarketingEmailCheckboxDiv
            {
                get
                {
                    return _marketingemailcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MarketingEmailCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("e3abd9cc-54b9-45a1-9bf9-141a9ab18028")]
            public virtual RepoItemInfo MarketingEmailCheckboxDivInfo
            {
                get
                {
                    return _marketingemailcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The PersonalDataCheckboxDiv item.
            /// </summary>
            [RepositoryItem("3f4881b2-5705-49f0-bf25-38d7b2d1244a")]
            public virtual Ranorex.DivTag PersonalDataCheckboxDiv
            {
                get
                {
                    return _personaldatacheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalDataCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("3f4881b2-5705-49f0-bf25-38d7b2d1244a")]
            public virtual RepoItemInfo PersonalDataCheckboxDivInfo
            {
                get
                {
                    return _personaldatacheckboxdivInfo;
                }
            }

            /// <summary>
            /// The AddToCartButton item.
            /// </summary>
            [RepositoryItem("145f3143-f3e4-4cf9-9a65-31ce6beb267b")]
            public virtual Ranorex.Button AddToCartButton
            {
                get
                {
                    return _addtocartbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddToCartButton item info.
            /// </summary>
            [RepositoryItemInfo("145f3143-f3e4-4cf9-9a65-31ce6beb267b")]
            public virtual RepoItemInfo AddToCartButtonInfo
            {
                get
                {
                    return _addtocartbuttonInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("30140022-9b65-4374-84e9-c4f939a146bc")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("30140022-9b65-4374-84e9-c4f939a146bc")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The ProceedToCheckoutButton item.
            /// </summary>
            [RepositoryItem("87145e4a-8258-4631-8aa9-bd75ad265f70")]
            public virtual Ranorex.SpanTag ProceedToCheckoutButton
            {
                get
                {
                    return _proceedtocheckoutbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProceedToCheckoutButton item info.
            /// </summary>
            [RepositoryItemInfo("87145e4a-8258-4631-8aa9-bd75ad265f70")]
            public virtual RepoItemInfo ProceedToCheckoutButtonInfo
            {
                get
                {
                    return _proceedtocheckoutbuttonInfo;
                }
            }

            /// <summary>
            /// The SearchInput item.
            /// </summary>
            [RepositoryItem("9802ff52-3124-481d-8de5-384343e9aa44")]
            public virtual Ranorex.InputTag SearchInput
            {
                get
                {
                    return _searchinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchInput item info.
            /// </summary>
            [RepositoryItemInfo("9802ff52-3124-481d-8de5-384343e9aa44")]
            public virtual RepoItemInfo SearchInputInfo
            {
                get
                {
                    return _searchinputInfo;
                }
            }

            /// <summary>
            /// The LogoutButton item.
            /// </summary>
            [RepositoryItem("ec3932f7-c41f-4335-b62f-4cbf1a883e25")]
            public virtual Ranorex.Button LogoutButton
            {
                get
                {
                    return _logoutbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LogoutButton item info.
            /// </summary>
            [RepositoryItemInfo("ec3932f7-c41f-4335-b62f-4cbf1a883e25")]
            public virtual RepoItemInfo LogoutButtonInfo
            {
                get
                {
                    return _logoutbuttonInfo;
                }
            }

            /// <summary>
            /// The MyAccountButton item.
            /// </summary>
            [RepositoryItem("7c14b9ca-221d-4a87-8076-2e1f24a83769")]
            public virtual Ranorex.PTag MyAccountButton
            {
                get
                {
                    return _myaccountbuttonInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MyAccountButton item info.
            /// </summary>
            [RepositoryItemInfo("7c14b9ca-221d-4a87-8076-2e1f24a83769")]
            public virtual MyAccountButtonInfoClass MyAccountButtonInfo
            {
                get
                {
                    return _myaccountbuttonInfo;
                }
            }

            /// <summary>
            /// The FirstProductNameInSearch item.
            /// </summary>
            [RepositoryItem("8a0628f8-34df-46d8-94ae-7ee4d756d0b0")]
            public virtual Ranorex.DivTag FirstProductNameInSearch
            {
                get
                {
                    return _firstproductnameinsearchInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FirstProductNameInSearch item info.
            /// </summary>
            [RepositoryItemInfo("8a0628f8-34df-46d8-94ae-7ee4d756d0b0")]
            public virtual RepoItemInfo FirstProductNameInSearchInfo
            {
                get
                {
                    return _firstproductnameinsearchInfo;
                }
            }

            /// <summary>
            /// The ProductNameSpan item.
            /// </summary>
            [RepositoryItem("9ab1077c-422a-444a-8fe4-6eeca5d38214")]
            public virtual Ranorex.SpanTag ProductNameSpan
            {
                get
                {
                    return _productnamespanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProductNameSpan item info.
            /// </summary>
            [RepositoryItemInfo("9ab1077c-422a-444a-8fe4-6eeca5d38214")]
            public virtual RepoItemInfo ProductNameSpanInfo
            {
                get
                {
                    return _productnamespanInfo;
                }
            }

            /// <summary>
            /// The ProductNameCartPage item.
            /// </summary>
            [RepositoryItem("3ce6aebc-722b-4549-ad7c-5bd29b78943f")]
            public virtual Ranorex.PTag ProductNameCartPage
            {
                get
                {
                    return _productnamecartpageInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ProductNameCartPage item info.
            /// </summary>
            [RepositoryItemInfo("3ce6aebc-722b-4549-ad7c-5bd29b78943f")]
            public virtual RepoItemInfo ProductNameCartPageInfo
            {
                get
                {
                    return _productnamecartpageInfo;
                }
            }

            /// <summary>
            /// The RegisterEmailInput item.
            /// </summary>
            [RepositoryItem("85df90b8-1a3b-4517-a07b-f17096ccda49")]
            public virtual Ranorex.InputTag RegisterEmailInput
            {
                get
                {
                    return _registeremailinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmailInput item info.
            /// </summary>
            [RepositoryItemInfo("85df90b8-1a3b-4517-a07b-f17096ccda49")]
            public virtual RepoItemInfo RegisterEmailInputInfo
            {
                get
                {
                    return _registeremailinputInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("7556e76c-f236-4a6a-bc49-bfbee4e070b1")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("7556e76c-f236-4a6a-bc49-bfbee4e070b1")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The UserNotLoggedInContainer item.
            /// </summary>
            [RepositoryItem("fcb005b8-73ca-4121-9846-634fef9f40db")]
            public virtual Ranorex.DivTag UserNotLoggedInContainer
            {
                get
                {
                    return _usernotloggedincontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UserNotLoggedInContainer item info.
            /// </summary>
            [RepositoryItemInfo("fcb005b8-73ca-4121-9846-634fef9f40db")]
            public virtual RepoItemInfo UserNotLoggedInContainerInfo
            {
                get
                {
                    return _usernotloggedincontainerInfo;
                }
            }

            /// <summary>
            /// The FirstProductLinkInSearchPage item.
            /// </summary>
            [RepositoryItem("cc9739c1-2ad2-49e2-8513-9477a7a6bbdb")]
            public virtual Ranorex.ATag FirstProductLinkInSearchPage
            {
                get
                {
                    return _firstproductlinkinsearchpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FirstProductLinkInSearchPage item info.
            /// </summary>
            [RepositoryItemInfo("cc9739c1-2ad2-49e2-8513-9477a7a6bbdb")]
            public virtual RepoItemInfo FirstProductLinkInSearchPageInfo
            {
                get
                {
                    return _firstproductlinkinsearchpageInfo;
                }
            }

            /// <summary>
            /// The FirstProductLinkInCartPage item.
            /// </summary>
            [RepositoryItem("562e393f-d3ee-4c03-8464-d3d86e336eaf")]
            public virtual Ranorex.ATag FirstProductLinkInCartPage
            {
                get
                {
                    return _firstproductlinkincartpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FirstProductLinkInCartPage item info.
            /// </summary>
            [RepositoryItemInfo("562e393f-d3ee-4c03-8464-d3d86e336eaf")]
            public virtual RepoItemInfo FirstProductLinkInCartPageInfo
            {
                get
                {
                    return _firstproductlinkincartpageInfo;
                }
            }

            /// <summary>
            /// The RegisterPage folder.
            /// </summary>
            [RepositoryFolder("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual TrendyolTestRepositoryFolders.RegisterPageFolder RegisterPage
            {
                get { return _registerpage; }
            }

            /// <summary>
            /// The ProductDetails folder.
            /// </summary>
            [RepositoryFolder("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual TrendyolTestRepositoryFolders.ProductDetailsFolder ProductDetails
            {
                get { return _productdetails; }
            }

            /// <summary>
            /// The CartPage folder.
            /// </summary>
            [RepositoryFolder("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual TrendyolTestRepositoryFolders.CartPageFolder CartPage
            {
                get { return _cartpage; }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual TrendyolTestRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }
        }

        /// <summary>
        /// The RegisterPageFolder folder.
        /// </summary>
        [RepositoryFolder("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
        public partial class RegisterPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _personalcheckboxdivInfo;
            RepoItemInfo _marketingcheckboxdivInfo;
            RepoItemInfo _registerbuttonInfo;

            /// <summary>
            /// Creates a new RegisterPage  folder.
            /// </summary>
            public RegisterPageFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterPage", "", parentFolder, 30000, null, false, "92ff70e5-3c16-4368-8ec6-a1252c5236f8", "")
            {
                _personalcheckboxdivInfo = new RepoItemInfo(this, "PersonalCheckboxDiv", ".//div[@class='personal-checkbox']", ".//div[#'login-register']//form/div[6]/div/div[1]", 30000, null, "49e66d49-8381-4708-a1a0-fe36dc994057");
                _marketingcheckboxdivInfo = new RepoItemInfo(this, "MarketingCheckboxDiv", ".//div[@class='marketing-checkbox']", ".//div[#'login-register']//form/div[5]/div/div[1]", 30000, null, "cb1d2aaf-e139-4612-b6b1-c9311b50efc6");
                _registerbuttonInfo = new RepoItemInfo(this, "RegisterButton", ".//form/button", ".//div[#'login-register']//form/button", 30000, null, "ea0e4a66-6c0b-4f1a-b677-e867cd149887");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("92ff70e5-3c16-4368-8ec6-a1252c5236f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PersonalCheckboxDiv item.
            /// </summary>
            [RepositoryItem("49e66d49-8381-4708-a1a0-fe36dc994057")]
            public virtual Ranorex.DivTag PersonalCheckboxDiv
            {
                get
                {
                    return _personalcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("49e66d49-8381-4708-a1a0-fe36dc994057")]
            public virtual RepoItemInfo PersonalCheckboxDivInfo
            {
                get
                {
                    return _personalcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The MarketingCheckboxDiv item.
            /// </summary>
            [RepositoryItem("cb1d2aaf-e139-4612-b6b1-c9311b50efc6")]
            public virtual Ranorex.DivTag MarketingCheckboxDiv
            {
                get
                {
                    return _marketingcheckboxdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MarketingCheckboxDiv item info.
            /// </summary>
            [RepositoryItemInfo("cb1d2aaf-e139-4612-b6b1-c9311b50efc6")]
            public virtual RepoItemInfo MarketingCheckboxDivInfo
            {
                get
                {
                    return _marketingcheckboxdivInfo;
                }
            }

            /// <summary>
            /// The RegisterButton item.
            /// </summary>
            [RepositoryItem("ea0e4a66-6c0b-4f1a-b677-e867cd149887")]
            public virtual Ranorex.ButtonTag RegisterButton
            {
                get
                {
                    return _registerbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RegisterButton item info.
            /// </summary>
            [RepositoryItemInfo("ea0e4a66-6c0b-4f1a-b677-e867cd149887")]
            public virtual RepoItemInfo RegisterButtonInfo
            {
                get
                {
                    return _registerbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ProductDetailsFolder folder.
        /// </summary>
        [RepositoryFolder("27698d01-8ea9-4b65-9edd-3224afe26aef")]
        public partial class ProductDetailsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addtofavoritesbtnInfo;

            /// <summary>
            /// Creates a new ProductDetails  folder.
            /// </summary>
            public ProductDetailsFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductDetails", "", parentFolder, 30000, null, false, "27698d01-8ea9-4b65-9edd-3224afe26aef", "")
            {
                _addtofavoritesbtnInfo = new RepoItemInfo(this, "AddToFavoritesBtn", ".//div[@class='container-right-content']//button[@class='fv']", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[5]/div/div/div[1]/button", 30000, null, "8171e99b-7f37-4cb1-af52-086de2980edf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("27698d01-8ea9-4b65-9edd-3224afe26aef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddToFavoritesBtn item.
            /// </summary>
            [RepositoryItem("8171e99b-7f37-4cb1-af52-086de2980edf")]
            public virtual Ranorex.ButtonTag AddToFavoritesBtn
            {
                get
                {
                    return _addtofavoritesbtnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToFavoritesBtn item info.
            /// </summary>
            [RepositoryItemInfo("8171e99b-7f37-4cb1-af52-086de2980edf")]
            public virtual RepoItemInfo AddToFavoritesBtnInfo
            {
                get
                {
                    return _addtofavoritesbtnInfo;
                }
            }
        }

        /// <summary>
        /// The CartPageFolder folder.
        /// </summary>
        [RepositoryFolder("09e73355-0b29-4956-9394-895219e011eb")]
        public partial class CartPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pcheckboxtextInfo;
            RepoItemInfo _kaydetvedevametInfo;
            RepoItemInfo _oedemeyapInfo;

            /// <summary>
            /// Creates a new CartPage  folder.
            /// </summary>
            public CartPageFolder(RepoGenBaseFolder parentFolder) :
                    base("CartPage", "", parentFolder, 30000, null, false, "09e73355-0b29-4956-9394-895219e011eb", "")
            {
                _pcheckboxtextInfo = new RepoItemInfo(this, "PCheckboxText", ".//div[#'p-layout']/aside/div/div[2]/section//span", ".//div[#'p-layout']/aside/div/div[2]/section/div/label/span", 30000, null, "d55e23da-dbdd-4421-937a-3cb34b09d962");
                _kaydetvedevametInfo = new RepoItemInfo(this, "KaydetVeDevamEt", ".//button[@innertext='Kaydet ve Devam Et']", ".//div[#'p-layout']//button[@innertext='Kaydet ve Devam Et']", 30000, null, "df87f721-3bd7-4788-841e-0141b997e9eb");
                _oedemeyapInfo = new RepoItemInfo(this, "OEdemeYap", ".//button[@innertext='Ödeme Yap']", ".//div[#'p-layout']//button[@innertext='Ödeme Yap']", 30000, null, "e4f650e4-66a3-4e03-a167-26525b497eeb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("09e73355-0b29-4956-9394-895219e011eb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PCheckboxText item.
            /// </summary>
            [RepositoryItem("d55e23da-dbdd-4421-937a-3cb34b09d962")]
            public virtual Ranorex.SpanTag PCheckboxText
            {
                get
                {
                    return _pcheckboxtextInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PCheckboxText item info.
            /// </summary>
            [RepositoryItemInfo("d55e23da-dbdd-4421-937a-3cb34b09d962")]
            public virtual RepoItemInfo PCheckboxTextInfo
            {
                get
                {
                    return _pcheckboxtextInfo;
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item.
            /// </summary>
            [RepositoryItem("df87f721-3bd7-4788-841e-0141b997e9eb")]
            public virtual Ranorex.ButtonTag KaydetVeDevamEt
            {
                get
                {
                    return _kaydetvedevametInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item info.
            /// </summary>
            [RepositoryItemInfo("df87f721-3bd7-4788-841e-0141b997e9eb")]
            public virtual RepoItemInfo KaydetVeDevamEtInfo
            {
                get
                {
                    return _kaydetvedevametInfo;
                }
            }

            /// <summary>
            /// The OEdemeYap item.
            /// </summary>
            [RepositoryItem("e4f650e4-66a3-4e03-a167-26525b497eeb")]
            public virtual Ranorex.ButtonTag OEdemeYap
            {
                get
                {
                    return _oedemeyapInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The OEdemeYap item info.
            /// </summary>
            [RepositoryItemInfo("e4f650e4-66a3-4e03-a167-26525b497eeb")]
            public virtual RepoItemInfo OEdemeYapInfo
            {
                get
                {
                    return _oedemeyapInfo;
                }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("75057fdc-53fe-44a0-ac72-159d02765518")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginemailinputInfo;
            RepoItemInfo _loginpasswordinputInfo;
            RepoItemInfo _loginbuttonInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 30000, null, false, "75057fdc-53fe-44a0-ac72-159d02765518", "")
            {
                _loginemailinputInfo = new RepoItemInfo(this, "LoginEmailInput", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "6f5e46d8-bfec-40db-8dec-831bd68382a4");
                _loginpasswordinputInfo = new RepoItemInfo(this, "LoginPasswordInput", ".//input[#'login-password-input']", ".//input[#'login-password-input']", 30000, null, "5636cfae-ee04-4b6d-8568-a3aa9efabb86");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//form/button", ".//div[#'login-register']//form/button/span[@innertext='Giriş Yap']", 30000, null, "998acbc8-a2bb-490b-b287-ed89a4098891");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75057fdc-53fe-44a0-ac72-159d02765518")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginEmailInput item.
            /// </summary>
            [RepositoryItem("6f5e46d8-bfec-40db-8dec-831bd68382a4")]
            public virtual Ranorex.InputTag LoginEmailInput
            {
                get
                {
                    return _loginemailinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmailInput item info.
            /// </summary>
            [RepositoryItemInfo("6f5e46d8-bfec-40db-8dec-831bd68382a4")]
            public virtual RepoItemInfo LoginEmailInputInfo
            {
                get
                {
                    return _loginemailinputInfo;
                }
            }

            /// <summary>
            /// The LoginPasswordInput item.
            /// </summary>
            [RepositoryItem("5636cfae-ee04-4b6d-8568-a3aa9efabb86")]
            public virtual Ranorex.InputTag LoginPasswordInput
            {
                get
                {
                    return _loginpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("5636cfae-ee04-4b6d-8568-a3aa9efabb86")]
            public virtual RepoItemInfo LoginPasswordInputInfo
            {
                get
                {
                    return _loginpasswordinputInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("998acbc8-a2bb-490b-b287-ed89a4098891")]
            public virtual Ranorex.Button LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("998acbc8-a2bb-490b-b287-ed89a4098891")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form", parentFolder, 30000, null, true, "f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f5c8c8e1-4e7e-4e3f-8aac-e82fd27c022c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
